import 'package:flutter_test/flutter_test.dart';
import 'package:saku/core/services/smart_transaction_parser.dart';

void main() {
  late SmartTransactionParser parser;

  setUp(() {
    parser = SmartTransactionParser();
  });

  group('SmartTransactionParser Tests', () {
    test('1. Kasus Mind Space Card (Bensin & Mi Ayam)', () {
      const rawText = '''
Daily Expenses for Fuel and Food Consumption
Voice memos 13/09/2026, 07.32

Transcription
Pembelian bensin sebesar Rp25.000 dan pembelian mi ayam serta es teh pada kemarin malam sebesar Rp29.000.

# Daily Life
Remarks
''';

      final results = parser.parse(rawText);

      expect(results.length, 2);

      // Transaksi 1: Bensin
      expect(results[0].feature, 'transaksi');
      expect(results[0].type, 'expense');
      expect(results[0].amount, 25000.0);
      expect(results[0].note, 'Bensin');

      // Transaksi 2: Mi ayam & es teh
      expect(results[1].feature, 'transaksi');
      expect(results[1].type, 'expense');
      expect(results[1].amount, 29000.0);
      expect(results[1].note, 'Mi ayam serta es teh');
    });

    test('2. Kasus Hutang (Pinjam dari seseorang)', () {
      const text = 'Pinjam uang dari Budi sebesar 200rb untuk bayar listrik';
      final results = parser.parse(text);

      expect(results.length, 1);
      expect(results[0].feature, 'hutang_piutang');
      expect(results[0].type, 'hutang');
      expect(results[0].amount, 200000.0);
      expect(results[0].contactName?.toLowerCase(), contains('budi'));
    });

    test('3. Kasus Piutang (Meminjamkan ke seseorang)', () {
      const text = 'Meminjamkan ke Andi 150rb';
      final results = parser.parse(text);

      expect(results.length, 1);
      expect(results[0].feature, 'hutang_piutang');
      expect(results[0].type, 'piutang');
      expect(results[0].amount, 150000.0);
      expect(results[0].contactName?.toLowerCase(), contains('andi'));
    });

    test('4. Kasus Transfer Antar Dompet', () {
      const text = 'Transfer dari BCA ke Gopay 50.000';
      final results = parser.parse(text);

      expect(results.length, 1);
      expect(results[0].feature, 'transfer');
      expect(results[0].amount, 50000.0);
      expect(results[0].fromWallet?.toLowerCase(), 'bca');
      expect(results[0].toWallet?.toLowerCase(), 'gojek');
    });

    test('4b. Kasus Transfer Uang / Pindah Uang Mind Space Card (Jago ke BNI)', () {
      const ocrTransfer = '''
Transfer of Two Hundred Twenty Six Thousand Rupi...
Voice memos 15/09/2026, 08.23

Transcription
Transfer uang dari Jago ke BNI sebesar Rp226.000.

# Finance and Economics
Remarks
Add a note to this memory
Generated by OPPO AI . For reference only.
Ask questions
''';

      final results = parser.parse(ocrTransfer);
      expect(results.length, 1);
      expect(results[0].feature, 'transfer');
      expect(results[0].amount, 226000.0);
      expect(results[0].fromWallet, 'Jago');
      expect(results[0].toWallet, 'BNI');

      // Teks natural langsung
      final t2 = parser.parse('Pindah uang dari Jago ke BNI sebesar 226rb');
      expect(t2[0].feature, 'transfer');
      expect(t2[0].amount, 226000.0);
      expect(t2[0].fromWallet, 'Jago');
      expect(t2[0].toWallet, 'BNI');

      // Top up dari rekening
      final t3 = parser.parse('Top up Dana dari Jago sebesar 100k');
      expect(t3[0].feature, 'transfer');
      expect(t3[0].amount, 100000.0);
      expect(t3[0].fromWallet, 'Jago');
      expect(t3[0].toWallet, 'Dana');

      // Transfer ke penerima pakai sumber
      final t4 = parser.parse('Transfer ke BNI pakai Jago 226000');
      expect(t4[0].feature, 'transfer');
      expect(t4[0].amount, 226000.0);
      expect(t4[0].fromWallet, 'Jago');
      expect(t4[0].toWallet, 'BNI');
    });

    test('5. Kasus Pemasukan (Gaji, Kiriman Uang, Penjualan, Bonus)', () {
      final t1 = parser.parse('Dapat transferan gaji bulanan sebesar 5.5 jt');
      expect(t1[0].feature, 'transaksi');
      expect(t1[0].type, 'income');
      expect(t1[0].amount, 5500000.0);
      expect(t1[0].category, 'Gaji');

      final t2 = parser.parse('Dikirimkan uang 500rb dari paman');
      expect(t2[0].feature, 'transaksi');
      expect(t2[0].type, 'income');
      expect(t2[0].amount, 500000.0);

      final t3 = parser.parse('Pendapatan jualan hari ini 250rb');
      expect(t3[0].feature, 'transaksi');
      expect(t3[0].type, 'income');
      expect(t3[0].amount, 250000.0);
      expect(t3[0].category, 'Penjualan');

      final t4 = parser.parse('Terima honor proyek freelance 1.5jt');
      expect(t4[0].feature, 'transaksi');
      expect(t4[0].type, 'income');
      expect(t4[0].amount, 1500000.0);
    });

    test('6. Kasus Format Nominal Singkatan (k, rb, jt)', () {
      expect(parser.parse('Beli kopi 25k')[0].amount, 25000.0);
      expect(parser.parse('Beli martabak 35rb')[0].amount, 35000.0);
      expect(parser.parse('Jual laptop 3.2 juta')[0].amount, 3200000.0);
      expect(parser.parse('Bayar wifi Rp 350.000')[0].amount, 350000.0);
    });

    test('7. Kasus Deteksi Wallet & Pembersihan Catatan (beli nasipadang 15k dengan jago)', () {
      final t1 = parser.parse('beli nasipadang 15k dengan jago');
      expect(t1.length, 1);
      expect(t1[0].feature, 'transaksi');
      expect(t1[0].type, 'expense');
      expect(t1[0].amount, 15000.0);
      expect(t1[0].category, 'Makanan & Minuman');
      expect(t1[0].wallet, 'Jago');
      expect(t1[0].note, 'Nasipadang');

      final t2 = parser.parse('Beli bensin pertalite 25rb pakai bca');
      expect(t2[0].amount, 25000.0);
      expect(t2[0].category, 'Transportasi');
      expect(t2[0].wallet, 'BCA');
      expect(t2[0].note, 'Bensin pertalite');

      final t3 = parser.parse('Makan siang bakso 20000 via gopay');
      expect(t3[0].amount, 20000.0);
      expect(t3[0].category, 'Makanan & Minuman');
      expect(t3[0].wallet, 'Gojek');
      expect(t3[0].note, 'Makan siang bakso');
    });

    test('8. Kasus Mind Space Card dengan Hashtag (# Shopping) dan Jus Alpukat', () {
      const ocrText = '''
Mind Space
Purchasing Avocado Juice Using BNI Payment Method
Source: Voice memos

Transcription
Pembelian jus alpukat seharga Rp10.000 menggunakan BNI.

# Shopping
''';

      final results = parser.parse(ocrText);
      expect(results.length, 1);
      expect(results[0].amount, 10000.0);
      expect(results[0].category, 'Makanan & Minuman');
      expect(results[0].wallet, 'BNI');
      expect(results[0].note, 'Jus alpukat');

      // Test jika format teks raw tanpa header tapi mengandung hashtag
      final rawResults = parser.parse('Pembelian jus alpukat seharga Rp10.000 menggunakan BNI. # Shopping');
      expect(rawResults.length, 1);
      expect(rawResults[0].amount, 10000.0);
      expect(rawResults[0].category, 'Makanan & Minuman');
      expect(rawResults[0].wallet, 'BNI');
      expect(rawResults[0].note, 'Jus alpukat');
    });

    test('9. Kasus Penyesuaian Saldo / Ngepasin Saldo (Berbagai Variasi Bahasa)', () {
      // 1. Pola Descriptive ("Saldo BNI seharusnya 200k", "Saldo BNI harusnya 200 ribu")
      final t1 = parser.parse('Saldo BNI seharusnya 200k');
      expect(t1.length, 1);
      expect(t1[0].feature, 'penyesuaian_saldo');
      expect(t1[0].amount, 200000.0);
      expect(t1[0].wallet, 'BNI');

      final t2 = parser.parse('Saldo BNI harusnya 200 ribu');
      expect(t2[0].feature, 'penyesuaian_saldo');
      expect(t2[0].amount, 200000.0);
      expect(t2[0].wallet, 'BNI');

      // 2. Pola Action / Imperative ("Ngepasin saldo BCA jadi 500rb", "Pasin dompet ke 100k")
      final t3 = parser.parse('Ngepasin saldo BCA jadi 500rb');
      expect(t3[0].feature, 'penyesuaian_saldo');
      expect(t3[0].amount, 500000.0);
      expect(t3[0].wallet, 'BCA');

      final t4 = parser.parse('Pasin dompet ke 100k');
      expect(t4[0].feature, 'penyesuaian_saldo');
      expect(t4[0].amount, 100000.0);
      expect(t4[0].wallet, 'Dompet Utama');

      final t5 = parser.parse('Sesuaikan saldo Mandiri menjadi 250.000');
      expect(t5[0].feature, 'penyesuaian_saldo');
      expect(t5[0].amount, 250000.0);
      expect(t5[0].wallet, 'Mandiri');

      // 3. Pola Riil / Fisik ("Saldo riil BNI ada 30.000", "Saldo fisik dompet 50rb")
      final t6 = parser.parse('Saldo riil BNI ada 30.000');
      expect(t6[0].feature, 'penyesuaian_saldo');
      expect(t6[0].amount, 30000.0);
      expect(t6[0].wallet, 'BNI');

      final t7 = parser.parse('Saldo fisik dompet 50rb');
      expect(t7[0].feature, 'penyesuaian_saldo');
      expect(t7[0].amount, 50000.0);
      expect(t7[0].wallet, 'Dompet Utama');

      // 4. Pola Locative ("Di BNI uangnya sekarang 30.000", "Duit di Jago aslinya tinggal 150rb")
      final t8 = parser.parse('Di BNI uangnya sekarang 30.000');
      expect(t8[0].feature, 'penyesuaian_saldo');
      expect(t8[0].amount, 30000.0);
      expect(t8[0].wallet, 'BNI');

      final t9 = parser.parse('Duit di Jago aslinya tinggal 150rb');
      expect(t9[0].feature, 'penyesuaian_saldo');
      expect(t9[0].amount, 150000.0);
      expect(t9[0].wallet, 'Jago');

      // 5. Pola Reverse ("BNI seharusnya 200k")
      final t10 = parser.parse('BNI seharusnya 200k');
      expect(t10[0].feature, 'penyesuaian_saldo');
      expect(t10[0].amount, 200000.0);
      expect(t10[0].wallet, 'BNI');

      // 6. Pola Mind Space Card OCR
      const ocrCard = '''
Mind Space
Card Title: Balance Adjustment
Source: Voice memos

Transcription
Ngepasin saldo BNI sebesar Rp200.000.

# Finance
''';
      final t11 = parser.parse(ocrCard);
      expect(t11.length, 1);
      expect(t11[0].feature, 'penyesuaian_saldo');
      expect(t11[0].amount, 200000.0);
      expect(t11[0].wallet, 'BNI');
    });

    test('10. Kasus Mind Space Multi-Transaksi (Batagor, Ayam, & Hutang Es Kelapa)', () {
      const mindSpaceCard = '''
Daily Expense Records for Food and Beverage Items
Source: Voice memos

Transcription
Pembelian batagor sebesar 14.000 dilakukan menggunakan BNI. Pembelian ayam sebesar 9.000 dilakukan menggunakan BNI. Pembelian es kelapa sebesar 6.000 belum dibayar kepada Dani.

# Shopping
''';

      final results = parser.parse(mindSpaceCard);

      expect(results.length, 3);

      // Item 1: Batagor (Pengeluaran Rp 14.000 via BNI)
      expect(results[0].feature, 'transaksi');
      expect(results[0].type, 'expense');
      expect(results[0].amount, 14000.0);
      expect(results[0].note, 'Batagor');
      expect(results[0].wallet, 'BNI');
      expect(results[0].category, 'Makanan & Minuman');

      // Item 2: Ayam (Pengeluaran Rp 9.000 via BNI)
      expect(results[1].feature, 'transaksi');
      expect(results[1].type, 'expense');
      expect(results[1].amount, 9000.0);
      expect(results[1].note, 'Ayam');
      expect(results[1].wallet, 'BNI');
      expect(results[1].category, 'Makanan & Minuman');

      // Item 3: Es Kelapa (Hutang Rp 6.000 kepada Dani)
      expect(results[2].feature, 'hutang_piutang');
      expect(results[2].type, 'hutang');
      expect(results[2].amount, 6000.0);
      expect(results[2].note, 'Es kelapa');
      expect(results[2].contactName, 'Dani');
    });
  });
}

