import '../models/voice_intent_model.dart';

/// Service untuk mengekstrak entitas finansial dari teks natural bahasa Indonesia
/// (baik dari transkripsi suara Mind Space, teks input, maupun hasil OCR gambar).
class SmartTransactionParser {
  /// Entry point utama: mem-parsing teks mentah menjadi daftar [VoiceIntentModel]
  List<VoiceIntentModel> parse(String rawText) {
    if (rawText.trim().isEmpty) return [];

    // 1. Ekstrak teks inti jika terdapat format Mind Space Card
    final cleanedText = _extractCoreTranscription(rawText);

    // 2. Partisi teks berdasarkan deteksi nominal (multi-transaksi)
    final segments = _splitIntoTransactionSegments(cleanedText);

    final results = <VoiceIntentModel>[];

    for (final segment in segments) {
      final parsed = _parseSingleSegment(segment);
      if (parsed != null) {
        results.add(parsed);
      }
    }

    return results;
  }

  /// Mengekstrak bagian transkripsi jika teks berasal dari export/kartu Mind Space
  String _extractCoreTranscription(String text) {
    final lines = text.split('\n');
    final transcriptionIndex = lines.indexWhere(
      (line) => RegExp(r'^(?:#+\s*)?(?:Transcription|Transkripsi)\b', caseSensitive: false).hasMatch(line.trim()),
    );

    if (transcriptionIndex != -1) {
      final relevantLines = <String>[];
      for (var i = transcriptionIndex + 1; i < lines.length; i++) {
        final line = lines[i].trim();
        // Berhenti jika menemui hashtag, tags Mind Space, remarks, source, atau footer
        if (line.startsWith('#') ||
            RegExp(r'^(?:Shopping|Daily Life|Food & Drink|Finance|Personal|Work|Life|Remarks|Generated by|Ask questions)\b', caseSensitive: false).hasMatch(line) ||
            line.toLowerCase().startsWith('source:')) {
          break;
        }
        if (line.isNotEmpty) {
          relevantLines.add(line);
        }
      }
      if (relevantLines.isNotEmpty) {
        return _cleanNoise(relevantLines.join(' '));
      }
    }

    // Jika bukan format kartu Mind Space, gunakan teks asli yang dibersihkan dari noise/hashtag
    return _cleanNoise(text);
  }

  /// Membersihkan noise seperti hashtag dan metadata Mind Space dari teks
  String _cleanNoise(String text) {
    var cleaned = text;
    // Buang baris atau potongan hashtag (# Shopping, #Daily Life, dsb.)
    cleaned = cleaned.replaceAll(RegExp(r'#\s*[\w\s&-]+', caseSensitive: false), ' ');
    // Buang footer teks Mind Space jika ada
    cleaned = cleaned.replaceAll(RegExp(r'\b(?:Remarks|Generated by|Ask questions)\b.*$', caseSensitive: false), ' ');
    return cleaned.trim();
  }

  /// Memecah teks menjadi segmen-segmen transaksi independen
  List<String> _splitIntoTransactionSegments(String text) {
    // Cari semua posisi kemunculan nominal uang di dalam teks
    final amountMatches = _findAmountMatches(text);

    if (amountMatches.length <= 1) {
      return [text];
    }

    final segments = <String>[];
    var lastCutIndex = 0;

    for (var i = 0; i < amountMatches.length - 1; i++) {
      final currentMatch = amountMatches[i];
      final nextMatch = amountMatches[i + 1];

      // Cari kata sambung pemisah antara match saat ini dan match berikutnya
      final betweenText = text.substring(currentMatch.end, nextMatch.start);
      final splitRegex = RegExp(r'\b(?:dan(?:\s+pembelian|\s+beli|\s+bayar|\s+transfer)?|serta(?:\s+pembelian|\s+beli)?|lalu|kemudian|terus|setelah itu)\b|[,\n;]', caseSensitive: false);
      final splitMatch = splitRegex.firstMatch(betweenText);

      int cutIndex;
      if (splitMatch != null) {
        cutIndex = currentMatch.end + splitMatch.start;
      } else {
        cutIndex = currentMatch.end + (betweenText.length ~/ 2);
      }

      final segment = text.substring(lastCutIndex, cutIndex).trim();
      if (segment.isNotEmpty) {
        segments.add(segment);
      }
      lastCutIndex = cutIndex;
    }

    final remaining = text.substring(lastCutIndex).trim();
    if (remaining.isNotEmpty) {
      segments.add(remaining);
    }

    return segments;
  }

  /// Menemukan semua match nominal dalam teks
  List<Match> _findAmountMatches(String text) {
    // Format: Rp25.000, Rp 25.000, 25.000, 25rb, 25ribu, 25k, 1.5jt, 1,5 juta
    final amountPattern = RegExp(
      r'(?:Rp\.?\s*)?\b\d{1,3}(?:\.\d{3})+(?:,\d+)?\b|(?:Rp\.?\s*)?\b\d+(?:[.,]\d+)?\s*(?:juta|jt|million|ribu|rb|k)\b|(?:Rp\.?\s*)\d+\b',
      caseSensitive: false,
    );
    return amountPattern.allMatches(text).toList();
  }

  /// Mem-parsing satu segmen kalimat menjadi satu [VoiceIntentModel]
  VoiceIntentModel? _parseSingleSegment(String segment) {
    final cleanSegment = segment.trim();
    if (cleanSegment.isEmpty) return null;

    final amount = _extractAmount(cleanSegment);
    final lower = cleanSegment.toLowerCase();

    // ── 1. Deteksi Hutang / Piutang ──────────────────────────────────────────
    // Kasus Hutang: pinjam dari [nama], ngutang ke [nama], dapat pinjaman dari [nama]
    final debtRegex = RegExp(
      r'\b(?:pinjam\s+(?:uang\s+)?dari|ngutang\s+ke|hutang\s+(?:ke|dari)|dapat\s+pinjaman\s+dari)\s+([A-Za-z0-9_\s]+?)(?:\s+sebesar|\s+sejumlah|\s+senilai|\s+sebanyak|\s+sebesar\s+rp|\s+rp|\s+\d|\s+buat|\s+untuk|$)',
      caseSensitive: false,
    );
    final debtMatch = debtRegex.firstMatch(cleanSegment);
    if (debtMatch != null) {
      final contact = _cleanContactName(debtMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'hutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'hutang', contact),
      );
    }

    // Kasus Piutang: meminjamkan ke [nama], pinjamkan ke [nama], kasih pinjam ke [nama], dipinjam oleh [nama]
    final loanRegex = RegExp(
      r'\b(?:meminjamkan\s+(?:uang\s+)?ke|pinjamkan\s+ke|kasih\s+pinjam\s+ke|pinjami|dipinjam\s+(?:oleh|sama))\s+([A-Za-z0-9_\s]+?)(?:\s+sebesar|\s+sejumlah|\s+senilai|\s+sebanyak|\s+sebesar\s+rp|\s+rp|\s+\d|\s+buat|\s+untuk|$)',
      caseSensitive: false,
    );
    final loanMatch = loanRegex.firstMatch(cleanSegment);
    if (loanMatch != null) {
      final contact = _cleanContactName(loanMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'piutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'piutang', contact),
      );
    }

    // Kasus Piutang alternatif: "[Nama] pinjam uang ke saya"
    final altLoanRegex = RegExp(
      r'\b([A-Za-z0-9_]+)\s+pinjam\s+(?:uang\s+)?(?:ke\s+saya|sama\s+saya)',
      caseSensitive: false,
    );
    final altLoanMatch = altLoanRegex.firstMatch(cleanSegment);
    if (altLoanMatch != null) {
      final contact = _cleanContactName(altLoanMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'piutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'piutang', contact),
      );
    }

    // ── 2. Deteksi Transfer Antar Dompet vs Pemasukan ──────────────────────
    final isIncome = _isIncomeIntent(lower);

    if (!isIncome) {
      // Pola 1: [transfer/pindah/kirim] [uang/saldo/dana] [dari] [From] ke [To]
      // Contoh: "Transfer uang dari Jago ke BNI sebesar Rp226.000", "Pindah dana dari BCA ke Gopay", "Tf uang Jago ke BNI"
      final transferFromToRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?(?:dari\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 2: [transfer/pindah/kirim] [uang/saldo/dana] ke [To] [dari/pakai/via] [From]
      // Contoh: "Transfer uang ke BNI dari Jago", "Transfer ke BNI pakai BCA 50rb"
      final transferToFromRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:dari|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 3: [top up/isi saldo] [To] [dari/pakai/via] [From]
      // Contoh: "Top up Dana dari Jago", "Topup gopay 50rb pakai BCA", "Isi saldo ShopeePay via Mandiri"
      final topupFromRegex = RegExp(
        r'\b(?:top\s*up|topup|isi\s+saldo)\s+(?:ke\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)(?:\s+(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*))?\s*(?:dari|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 4: [top up/isi saldo] [To] (tanpa asal)
      // Contoh: "Top up Gopay 50rb", "Isi saldo ShopeePay 100k"
      final topupToOnlyRegex = RegExp(
        r'\b(?:top\s*up|topup|isi\s+saldo)\s+(?:ke\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 5: [transfer/pindah/kirim] [uang/saldo/dana] ke [To] (tanpa asal)
      // Contoh: "Transfer uang ke BNI sebesar 200rb", "Pindah saldo ke BCA"
      final transferToOnlyRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      final matchFromTo = transferFromToRegex.firstMatch(cleanSegment);
      final matchToFrom = transferToFromRegex.firstMatch(cleanSegment);
      final matchTopupFrom = topupFromRegex.firstMatch(cleanSegment);
      final matchTopupToOnly = topupToOnlyRegex.firstMatch(cleanSegment);
      final matchTransferToOnly = transferToOnlyRegex.firstMatch(cleanSegment);

      final isTransferPhrase = RegExp(
        r'\b(?:transfer\s+uang|pindah\s+uang|pindah\s+saldo|transfer\s+saldo|kirim\s+uang|kirim\s+saldo|tf\s+uang|top\s*up|isi\s+saldo)\b',
        caseSensitive: false,
      ).hasMatch(cleanSegment);

      if (matchFromTo != null || matchToFrom != null || matchTopupFrom != null || matchTopupToOnly != null || matchTransferToOnly != null || isTransferPhrase) {
        String? fromW;
        String? toW;

        if (matchFromTo != null) {
          fromW = _cleanWalletCandidate(matchFromTo.group(1));
          toW = _cleanWalletCandidate(matchFromTo.group(2));
        } else if (matchToFrom != null) {
          toW = _cleanWalletCandidate(matchToFrom.group(1));
          fromW = _cleanWalletCandidate(matchToFrom.group(2));
        } else if (matchTopupFrom != null) {
          toW = _cleanWalletCandidate(matchTopupFrom.group(1));
          fromW = _cleanWalletCandidate(matchTopupFrom.group(2));
        } else if (matchTopupToOnly != null) {
          toW = _cleanWalletCandidate(matchTopupToOnly.group(1));
        } else if (matchTransferToOnly != null) {
          toW = _cleanWalletCandidate(matchTransferToOnly.group(1));
        }

        // Jika fromW belum terdeteksi dari pola khusus, cari dari klausa preposisi "dari [wallet]" atau wallet umum
        fromW ??= _extractSourceWalletForTransfer(cleanSegment, excludedWallet: toW);

        final normFrom = fromW != null ? _normalizeWalletName(fromW) : null;
        final normTo = toW != null ? _normalizeWalletName(toW) : null;

        return VoiceIntentModel(
          feature: 'transfer',
          amount: amount,
          fromWallet: normFrom,
          toWallet: normTo,
          note: _extractNote(cleanSegment, 'transfer', null, normFrom, normTo),
        );
      }
    }

    // ── 3. Deteksi Pemasukan (Income) ─────────────────────────────────────────
    if (isIncome) {
      final category = _detectCategory(lower, isIncome: true);
      final wallet = _extractWallet(cleanSegment);
      return VoiceIntentModel(
        feature: 'transaksi',
        type: 'income',
        amount: amount,
        category: category,
        wallet: wallet,
        note: _extractNote(cleanSegment, 'income', null, wallet),
      );
    }

    // ── 4. Default: Pengeluaran (Expense) ────────────────────────────────────
    final category = _detectCategory(lower, isIncome: false);
    final wallet = _extractWallet(cleanSegment);
    return VoiceIntentModel(
      feature: 'transaksi',
      type: 'expense',
      amount: amount,
      category: category,
      wallet: wallet,
      note: _extractNote(cleanSegment, 'expense', null, wallet),
    );
  }

  /// Ekstraksi nilai nominal double dari kalimat
  double? _extractAmount(String text) {
    // 1. Kasus dengan satuan juta: "1.5 jt", "2 juta", "1,5juta"
    final jtMatch = RegExp(r'(\d+(?:[.,]\d+)?)\s*(?:juta|jt|million)\b', caseSensitive: false).firstMatch(text);
    if (jtMatch != null) {
      final numStr = jtMatch.group(1)!.replaceAll(',', '.');
      final val = double.tryParse(numStr);
      if (val != null) return val * 1000000;
    }

    // 2. Kasus dengan satuan ribu: "25rb", "25 ribu", "50k", "10.5 rb"
    final rbMatch = RegExp(r'(\d+(?:[.,]\d+)?)\s*(?:ribu|rb|k)\b', caseSensitive: false).firstMatch(text);
    if (rbMatch != null) {
      final numStr = rbMatch.group(1)!.replaceAll(',', '.');
      final val = double.tryParse(numStr);
      if (val != null) return val * 1000;
    }

    // 3. Format ribuan bertitik: "Rp25.000", "25.000", "1.500.000"
    final thousandMatch = RegExp(r'(?:Rp\.?\s*)?(\d{1,3}(?:\.\d{3})+(?:,\d+)?)', caseSensitive: false).firstMatch(text);
    if (thousandMatch != null) {
      final cleanNum = thousandMatch.group(1)!.replaceAll('.', '').replaceAll(',', '.');
      final val = double.tryParse(cleanNum);
      if (val != null) return val;
    }

    // 4. Format angka polos: "Rp 25000", "sebesar 50000"
    final plainMatch = RegExp(r'(?:Rp\.?\s*|sebesar\s+|seharga\s+|sejumlah\s+)(\d+)\b', caseSensitive: false).firstMatch(text);
    if (plainMatch != null) {
      return double.tryParse(plainMatch.group(1)!);
    }

    // 5. Fallback angka apa saja di atas 100
    final anyNumMatch = RegExp(r'\b(\d{4,})\b').firstMatch(text);
    if (anyNumMatch != null) {
      return double.tryParse(anyNumMatch.group(1)!);
    }

    return null;
  }

  /// Cek apakah kalimat mengindikasikan pemasukan
  bool _isIncomeIntent(String text) {
    const incomeKeywords = [
      'gaji',
      'salary',
      'upah',
      'honor',
      'penghasilan',
      'pendapatan',
      'pemasukan',
      'income',
      'terima uang',
      'dapat uang',
      'dapat transfer',
      'ditransfer',
      'dikirimkan uang',
      'dikirim uang',
      'dikirimi uang',
      'dapat kiriman',
      'terima transfer',
      'bonus',
      'thr',
      'cashback',
      'komisi',
      'freelance',
      'proyek',
      'hasil jualan',
      'jual',
      'jualan',
      'laba',
      'profit',
      'omset',
      'omzet',
      'dividen',
      'hadiah',
      'gift',
      'angpao',
    ];
    for (final kw in incomeKeywords) {
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return true;
      }
    }
    return false;
  }

  /// Deteksi kategori otomatis dari kata kunci
  String? _detectCategory(String text, {required bool isIncome}) {
    if (isIncome) {
      if (text.contains('jual') || text.contains('jualan') || text.contains('dagang') || text.contains('bisnis') || text.contains('omset') || text.contains('omzet') || text.contains('freelance') || text.contains('komisi') || text.contains('proyek')) {
        return 'Penjualan';
      }
      if (text.contains('dividen') || text.contains('investasi') || text.contains('saham') || text.contains('crypto') || text.contains('reksadana') || text.contains('bunga')) {
        return 'Investasi';
      }
      if (text.contains('bonus') || text.contains('thr') || text.contains('hadiah') || text.contains('gift') || text.contains('angpao') || text.contains('reward') || text.contains('cashback')) {
        return 'Bonus';
      }
      if (text.contains('gaji') || text.contains('salary') || text.contains('upah') || text.contains('honor') || text.contains('penghasilan') || text.contains('pendapatan')) {
        return 'Gaji';
      }
      if (text.contains('kirim') || text.contains('transfer') || text.contains('dikirimi')) {
        return 'Hadiah';
      }
      return 'Lainnya';
    }

    // Expense Categories
    const categoryMap = <String, List<String>>{
      'Makanan & Minuman': [
        'makan',
        'minum',
        'sarapan',
        'siang',
        'malam',
        'jus',
        'alpukat',
        'avocado',
        'juice',
        'smoothie',
        'kopi',
        'coffee',
        'teh',
        'es teh',
        'esteh',
        'boba',
        'susu',
        'milk',
        'yogurt',
        'air mineral',
        'aqua',
        'nasipadang',
        'nasi padang',
        'nasi',
        'nasgor',
        'padang',
        'mi ayam',
        'mie ayam',
        'miayam',
        'mieayam',
        'mie',
        'bakso',
        'ayam',
        'bebek',
        'ikan',
        'seafood',
        'kafe',
        'cafe',
        'resto',
        'restoran',
        'jajan',
        'snack',
        'cemilan',
        'burger',
        'pizza',
        'gorengan',
        'martabak',
        'sate',
        'soto',
        'pecel',
        'geprek',
        'seblak',
        'batagor',
        'siomay',
        'cilok',
        'cireng',
        'roti',
        'toast',
        'donat',
        'kue',
        'es krim',
        'ice cream',
        'gelato',
        'dimsum',
        'ramen',
        'sushi',
        'pasta',
        'steak',
        'warteg',
        'gofood',
        'grabfood',
        'shopeefood',
        'buah',
        'sayur',
      ],
      'Transportasi': [
        'bensin',
        'pertalite',
        'pertamax',
        'solar',
        'bbm',
        'parkir',
        'tol',
        'gojek',
        'grab',
        'ojol',
        'maxim',
        'indrive',
        'angkot',
        'busway',
        'transjakarta',
        'kereta',
        'krl',
        'mrt',
        'lrt',
        'tiket',
        'tambal ban',
        'cuci motor',
        'cuci mobil',
        'service',
        'servis',
        'oli',
      ],
      'Belanja': [
        'belanja',
        'shopping',
        'baju',
        'kaos',
        'celana',
        'sepatu',
        'tas',
        'supermarket',
        'minimarket',
        'indomaret',
        'alfamart',
        'alfamidi',
        'shopee',
        'tokopedia',
        'lazada',
        'tiktok shop',
        'skincare',
        'sabun',
        'shampoo',
        'odol',
        'deterjen',
        'mall',
      ],
      'Tagihan & Utilitas': [
        'listrik',
        'token',
        'pln',
        'air',
        'pdam',
        'wifi',
        'indihome',
        'biznet',
        'first media',
        'pulsa',
        'paket data',
        'kuota',
        'bpjs',
        'pajak',
        'asuransi',
        'tagihan',
        'iuran',
        'sewa',
        'kost',
        'kos',
        'kontrakan',
      ],
      'Hiburan': [
        'bioskop',
        'cinema',
        'xxi',
        'cgv',
        'nonton',
        'film',
        'game',
        'topup game',
        'steam',
        'playstation',
        'spotify',
        'netflix',
        'youtube',
        'disney',
        'liburan',
        'staycation',
        'hotel',
        'wisata',
        'karaoke',
      ],
      'Kesehatan': [
        'obat',
        'dokter',
        'rumah sakit',
        'rs',
        'apotek',
        'vitamin',
        'klinik',
        'periksa',
        'terapi',
        'rapid',
        'masker',
      ],
      'Pendidikan': [
        'buku',
        'kursus',
        'course',
        'sekolah',
        'kuliah',
        'spp',
        'les',
        'ujian',
        'seminar',
        'workshop',
        'alat tulis',
      ],
    };

    for (final entry in categoryMap.entries) {
      for (final kw in entry.value) {
        if (RegExp('\\b${RegExp.escape(kw)}\\b', caseSensitive: false).hasMatch(text) ||
            (kw.length >= 4 && text.contains(kw.toLowerCase()))) {
          return entry.key;
        }
      }
    }

    return 'Lainnya';
  }

  /// Membersihkan nama kontak dari kata sambung
  String _cleanContactName(String? raw) {
    if (raw == null) return '';
    var name = raw.trim();
    // Buang preposisi di ujung
    name = name.replaceAll(RegExp(r'\s+(?:sebesar|sejumlah|senilai|rp|\d+).*$', caseSensitive: false), '');
    return name.trim();
  }

  /// Membersihkan kandidat nama wallet dari kata-kata umum
  String? _cleanWalletCandidate(String? raw) {
    if (raw == null) return null;
    final name = raw.replaceAll(RegExp(r'^(?:rekening|bank|dompet|akun|kartu)\s+', caseSensitive: false), '').trim();
    final lower = name.toLowerCase();
    const nonWalletWords = [
      'uang',
      'saldo',
      'sebesar',
      'sejumlah',
      'senilai',
      'rp',
      'ke',
      'dari',
      'saya',
      'kamu',
      'dia',
      'pindah',
      'transfer',
    ];
    if (nonWalletWords.contains(lower) || RegExp(r'^\d').hasMatch(lower)) {
      return null;
    }
    return name;
  }

  /// Ekstraksi wallet asal jika kalimat transfer tidak memiliki pola regex langsung
  String? _extractSourceWalletForTransfer(String text, {String? excludedWallet}) {
    // 1. Coba cari preposisi "dari [wallet]" atau "pakai [wallet]"
    final prepRegex = RegExp(
      r'\b(?:dari|pakai|pake|via|lewat|menggunakan|melalui)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?([A-Za-z0-9_]+)\b',
      caseSensitive: false,
    );
    final match = prepRegex.firstMatch(text);
    if (match != null) {
      final candidate = _cleanWalletCandidate(match.group(1));
      if (candidate != null && (excludedWallet == null || candidate.toLowerCase() != excludedWallet.toLowerCase())) {
        return candidate;
      }
    }

    // 2. Cek keyword wallet populer jika tidak sama dengan destination wallet
    const knownWallets = [
      'jago',
      'bca',
      'bri',
      'bni',
      'mandiri',
      'cimb',
      'permata',
      'seabank',
      'blu',
      'jenius',
      'bsi',
      'gopay',
      'gojek',
      'ovo',
      'dana',
      'shopeepay',
      'spay',
      'linkaja',
      'cash',
      'tunai',
      'dompet',
    ];
    for (final kw in knownWallets) {
      if (excludedWallet != null && kw.toLowerCase() == excludedWallet.toLowerCase()) {
        continue;
      }
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return kw;
      }
    }

    return null;
  }

  /// Ekstraksi nama rekening / wallet dari preposisi atau nama bank/e-wallet populer
  String? _extractWallet(String text) {
    // 1. Pola preposisi eksplisit: "dengan jago", "pakai bca", "pake gopay", "via ovo", "lewat dana", "dari dompet", "menggunakan spay", "pake rekening bni"
    final prepRegex = RegExp(
      r'\b(?:dengan|pakai|pake|via|lewat|menggunakan|by|melalui|dari)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?([A-Za-z0-9_]+(?:\s+[A-Za-z0-9_]+)?)\b',
      caseSensitive: false,
    );

    final match = prepRegex.firstMatch(text);
    if (match != null) {
      final candidate = match.group(1)!.trim();
      final lower = candidate.toLowerCase();
      const nonWalletWords = [
        'cepat',
        'mudah',
        'senang',
        'teman',
        'keluarga',
        'kawan',
        'uang',
        'rupiah',
        'sebesar',
        'sejumlah',
        'harga',
        'kemarin',
        'tadi',
        'malam',
        'siang',
        'pagi',
        'sore',
      ];
      if (!nonWalletWords.contains(lower) && !RegExp(r'^\d').hasMatch(lower)) {
        return _normalizeWalletName(candidate);
      }
    }

    // 2. Pola nama e-wallet / bank populer langsung jika ada di teks
    const knownWallets = [
      'jago',
      'bca',
      'bri',
      'bni',
      'mandiri',
      'cimb',
      'permata',
      'seabank',
      'blu',
      'jenius',
      'bsi',
      'gopay',
      'gojek',
      'ovo',
      'dana',
      'shopeepay',
      'spay',
      'linkaja',
      'cash',
      'tunai',
      'dompet',
    ];
    for (final kw in knownWallets) {
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return _normalizeWalletName(kw);
      }
    }

    return null;
  }

  /// Normalisasi nama wallet agar rapi dan kapitalisasi tepat
  String _normalizeWalletName(String raw) {
    final clean = raw.replaceAll(RegExp(r'^(?:rekening|bank|dompet|akun|kartu)\s+', caseSensitive: false), '').trim();
    final lower = clean.toLowerCase();
    switch (lower) {
      case 'jago':
      case 'bank jago':
        return 'Jago';
      case 'bca':
      case 'bank bca':
        return 'BCA';
      case 'bri':
      case 'bank bri':
        return 'BRI';
      case 'bni':
      case 'bank bni':
        return 'BNI';
      case 'mandiri':
      case 'bank mandiri':
        return 'Mandiri';
      case 'seabank':
      case 'sea bank':
        return 'SeaBank';
      case 'blu':
      case 'blu bca':
        return 'blu';
      case 'jenius':
      case 'bank btpn':
        return 'Jenius';
      case 'bsi':
      case 'bank bsi':
        return 'BSI';
      case 'cimb':
      case 'cimb niaga':
        return 'CIMB Niaga';
      case 'permata':
      case 'bank permata':
        return 'Permata';
      case 'gopay':
      case 'go-pay':
      case 'gojek':
        return 'Gojek';
      case 'ovo':
        return 'OVO';
      case 'dana':
        return 'Dana';
      case 'shopeepay':
      case 'shopee pay':
      case 'spay':
        return 'ShopeePay';
      case 'linkaja':
      case 'link aja':
        return 'LinkAja';
      case 'cash':
      case 'tunai':
      case 'dompet':
        return 'Dompet Utama';
      default:
        return clean.split(' ').map((w) => w.isNotEmpty ? w[0].toUpperCase() + w.substring(1) : '').join(' ');
    }
  }

  /// Membersihkan teks kalimat menjadi catatan (note) yang ringkas (mis: "Bensin", "Mi ayam serta es teh")
  String _extractNote(String segment, String intentType, String? contact, [String? wallet, String? toWallet]) {
    var note = segment.trim();

    // 1. Buang semua format hashtag atau tag metadata (misal: # Shopping, #Daily Life, dsb.)
    note = note.replaceAll(RegExp(r'#\s*[\w\s&-]+', caseSensitive: false), ' ').trim();

    // 2. Buang tag kategori Mind Space umum yang sering tertinggal di ujung / tengah
    note = note.replaceAll(RegExp(r'\b(?:Shopping|Daily Life|Food & Drink|Finance|Personal|Work|Life|Remarks)\b', caseSensitive: false), ' ').trim();

    // 3. Buang klausa nominal di mana pun berada (misal: "sebesar Rp25.000", "Rp 25.000", "25rb", "50k", dsb.)
    note = note.replaceAll(RegExp(r'\s*(?:sebesar|sejumlah|senilai|seharga|nominal|total|harga)?\s*(?:Rp\.?\s*)?\d[\d.,]*\s*(?:juta|jt|million|ribu|rb|k)?', caseSensitive: false), ' ').trim();

    // 4. Khusus transfer: bersihkan kata kerja transfer dan entitas wallet
    if (intentType == 'transfer') {
      note = note.replaceAll(RegExp(r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf|top\s*up|topup|isi\s+saldo)\s+(?:uang|saldo|dana)?', caseSensitive: false), ' ').trim();
      note = note.replaceAll(RegExp(r'\b(?:dari|ke|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?[A-Za-z0-9_]+', caseSensitive: false), ' ').trim();
      if (toWallet != null && toWallet.isNotEmpty) {
        note = note.replaceAll(RegExp('\\b${RegExp.escape(toWallet)}\\b', caseSensitive: false), ' ').trim();
      }
    }

    // 5. Buang klausa metode pembayaran / wallet (misal: "dengan jago", "pakai bca", "via gopay", "pake dana", "menggunakan BNI")
    note = note.replaceAll(RegExp(r'\s*(?:dengan|pakai|pake|via|lewat|menggunakan|by|melalui|dari)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?[A-Za-z0-9_]+(?:\s+[A-Za-z0-9_]+)?', caseSensitive: false), ' ').trim();

    if (wallet != null && wallet.isNotEmpty) {
      note = note.replaceAll(RegExp('\\b${RegExp.escape(wallet)}\\b', caseSensitive: false), ' ').trim();
    }

    // 6. Buang sisa-sisa pola titik nominal seperti ".000" atau ",00"
    note = note.replaceAll(RegExp(r'[.,]\d{2,3}\b'), ' ').trim();

    // 7. Buang keterangan waktu umum
    note = note.replaceAll(RegExp(r'\s+(?:pada\s+)?(?:kemarin|tadi|semalam|hari ini|siang ini|pagi ini|malam ini|sore ini)(?:\s+(?:pagi|siang|sore|malam))?', caseSensitive: false), ' ').trim();

    // 8. Buang kata sambung & kata kerja aksi di awal kalimat berulang kali
    var prev = '';
    while (prev != note) {
      prev = note;
      note = note.replaceFirst(RegExp(r'^(?:dan|serta|lalu|kemudian|terus|setelah itu)\s+', caseSensitive: false), '').trim();
      note = note.replaceFirst(RegExp(r'^(?:pembelian|beli|membeli|bayar|membayar|pembayaran|isi|order|pesan|jajan|belanja|dapat|terima|kirim)\s+', caseSensitive: false), '').trim();
    }

    // 9. Bersihkan sisa tanda baca liar di tengah atau ujung (misal "jus alpukat . " -> "jus alpukat")
    note = note.replaceAll(RegExp(r'\s+[.,;:!?]+\s*'), ' ');
    note = note.replaceAll(RegExp(r'^[^\w]+|[^\w]+$'), ' ').trim();

    // 10. Kompres spasi ganda
    note = note.replaceAll(RegExp(r'\s+'), ' ');

    // 11. Capitalize huruf pertama & fallback cerdas
    if (note.isEmpty) {
      switch (intentType) {
        case 'hutang':
          return 'Hutang ke ${contact ?? 'seseorang'}';
        case 'piutang':
          return 'Piutang ke ${contact ?? 'seseorang'}';
        case 'transfer':
          if (toWallet != null && toWallet.isNotEmpty) {
            return 'Transfer ke $toWallet';
          }
          return 'Transfer dana';
        case 'income':
          return 'Pemasukan';
        default:
          return 'Pengeluaran';
      }
    }

    return note[0].toUpperCase() + note.substring(1);
  }
}
