import '../models/voice_intent_model.dart';

/// Service untuk mengekstrak entitas finansial dari teks natural bahasa Indonesia
/// (baik dari transkripsi suara Mind Space, teks input, maupun hasil OCR gambar).
class SmartTransactionParser {
  /// Entry point utama: mem-parsing teks mentah menjadi daftar [VoiceIntentModel]
  List<VoiceIntentModel> parse(String rawText) {
    if (rawText.trim().isEmpty) return [];

    // 1. Ekstrak teks inti jika terdapat format Mind Space Card
    final cleanedText = _extractCoreTranscription(rawText);

    // 2. Partisi teks berdasarkan deteksi nominal (multi-transaksi)
    final segments = _splitIntoTransactionSegments(cleanedText);

    final results = <VoiceIntentModel>[];

    for (final segment in segments) {
      final parsed = _parseSingleSegment(segment);
      if (parsed != null) {
        results.add(parsed);
      }
    }

    return results;
  }

  /// Mengekstrak bagian transkripsi jika teks berasal dari export/kartu Mind Space
  String _extractCoreTranscription(String text) {
    final lines = text.split('\n');
    final transcriptionIndex = lines.indexWhere(
      (line) => RegExp(r'^(?:#+\s*)?(?:Transcription|Transkripsi)\b', caseSensitive: false).hasMatch(line.trim()),
    );

    if (transcriptionIndex != -1) {
      final relevantLines = <String>[];
      for (var i = transcriptionIndex + 1; i < lines.length; i++) {
        final line = lines[i].trim();
        // Berhenti jika menemui hashtag, tags Mind Space, remarks, source, atau footer
        if (line.startsWith('#') ||
            RegExp(r'^(?:Shopping|Daily Life|Food & Drink|Finance|Personal|Work|Life|Remarks|Generated by|Ask questions)\b', caseSensitive: false).hasMatch(line) ||
            line.toLowerCase().startsWith('source:')) {
          break;
        }
        if (line.isNotEmpty) {
          relevantLines.add(line);
        }
      }
      if (relevantLines.isNotEmpty) {
        return _cleanNoise(relevantLines.join(' '));
      }
    }

    // Jika bukan format kartu Mind Space, gunakan teks asli yang dibersihkan dari noise/hashtag
    return _cleanNoise(text);
  }

  /// Membersihkan noise seperti hashtag dan metadata Mind Space dari teks
  String _cleanNoise(String text) {
    var cleaned = text;
    // Buang baris header Mind Space
    cleaned = cleaned.replaceAll(RegExp(r'^(?:Daily\s+Expense\s+Records?[^\n]*|Daily\s+Expenses?[^\n]*|Transfer\s+of[^\n]*)\s*', caseSensitive: false, multiLine: true), ' ');
    cleaned = cleaned.replaceAll(RegExp(r'^(?:Source:\s*Voice\s*memos|Voice\s*memos)[^\n]*\s*', caseSensitive: false, multiLine: true), ' ');
    // Buang baris atau potongan hashtag (# Shopping, #Daily Life, dsb.)
    cleaned = cleaned.replaceAll(RegExp(r'#\s*[\w\s&-]+', caseSensitive: false), ' ');
    // Buang footer teks Mind Space jika ada
    cleaned = cleaned.replaceAll(RegExp(r'\b(?:Remarks|Generated by|Ask questions)\b.*$', caseSensitive: false), ' ');
    return cleaned.trim();
  }

  /// Memecah teks menjadi segmen-segmen transaksi independen
  List<String> _splitIntoTransactionSegments(String text) {
    // Cari semua posisi kemunculan nominal uang di dalam teks
    final amountMatches = _findAmountMatches(text);

    if (amountMatches.length <= 1) {
      return [text];
    }

    final segments = <String>[];
    var lastCutIndex = 0;

    for (var i = 0; i < amountMatches.length - 1; i++) {
      final currentMatch = amountMatches[i];
      final nextMatch = amountMatches[i + 1];

      // Cari pemisah kalimat / klausa antara match saat ini dan match berikutnya
      final betweenText = text.substring(currentMatch.end, nextMatch.start);

      // Prioritas 1: Tanda titik diikuti spasi atau pemisah kalimat jelas
      final dotRegex = RegExp(r'\.\s+(?=[A-Za-z0-9])');
      final dotMatch = dotRegex.firstMatch(betweenText);

      // Prioritas 2: Baris baru atau titik koma
      final newlineOrSemiRegex = RegExp(r'[\n;]+');
      final newlineOrSemiMatch = newlineOrSemiRegex.firstMatch(betweenText);

      // Prioritas 3: Kata sambung atau kata pembuka transaksi baru
      final splitRegex = RegExp(
        r'\b(?:dan(?:\s+pembelian|\s+beli|\s+bayar|\s+transfer)?|serta(?:\s+pembelian|\s+beli)?|lalu|kemudian|terus|setelah\s+itu)\b|,\s*(?:dan|serta|lalu|kemudian|terus|setelah\s+itu|pembelian|beli|bayar|transfer)\b|(?<=\S\s+)\b(?:pembelian|beli|transfer|top\s*up|isi\s+saldo|pinjam|ngutang)\b',
        caseSensitive: false,
      );
      final splitMatch = splitRegex.firstMatch(betweenText);

      int cutIndex;
      if (dotMatch != null) {
        // Potong tepat setelah tanda titik
        cutIndex = currentMatch.end + dotMatch.start + 1;
      } else if (newlineOrSemiMatch != null) {
        cutIndex = currentMatch.end + newlineOrSemiMatch.start;
      } else if (splitMatch != null) {
        cutIndex = currentMatch.end + splitMatch.start;
      } else {
        cutIndex = currentMatch.end + (betweenText.length ~/ 2);
      }

      final segment = text.substring(lastCutIndex, cutIndex).trim();
      if (segment.isNotEmpty) {
        segments.add(segment);
      }
      lastCutIndex = cutIndex;
    }

    final remaining = text.substring(lastCutIndex).trim();
    if (remaining.isNotEmpty) {
      segments.add(remaining);
    }

    return segments;
  }

  /// Menemukan semua match nominal dalam teks
  List<Match> _findAmountMatches(String text) {
    // Format: Rp25.000, Rp 25.000, 25.000, 25rb, 25ribu, 25k, 1.5jt, 1,5 juta
    final amountPattern = RegExp(
      r'(?:Rp\.?\s*)?\b\d{1,3}(?:\.\d{3})+(?:,\d+)?\b|(?:Rp\.?\s*)?\b\d+(?:[.,]\d+)?\s*(?:juta|jt|million|ribu|rb|k)\b|(?:Rp\.?\s*)\d+\b',
      caseSensitive: false,
    );
    return amountPattern.allMatches(text).toList();
  }

  /// Mem-parsing satu segmen kalimat menjadi satu [VoiceIntentModel]
  VoiceIntentModel? _parseSingleSegment(String segment) {
    final cleanSegment = segment.trim();
    if (cleanSegment.isEmpty) return null;

    final amount = _extractAmount(cleanSegment);
    final date = _extractDate(cleanSegment);
    final lower = cleanSegment.toLowerCase();

    // ── 1. Deteksi Hutang / Piutang ──────────────────────────────────────────
    // Kasus Hutang 1: pinjam dari [nama], ngutang ke [nama], dapat pinjaman dari [nama]
    final debtRegex = RegExp(
      r'\b(?:pinjam\s+(?:uang\s+)?dari|ngutang\s+ke|hutang\s+(?:ke|dari)|dapat\s+pinjaman\s+dari)\s+([A-Za-z0-9_\s]+?)(?:\s+sebesar|\s+sejumlah|\s+senilai|\s+sebanyak|\s+sebesar\s+rp|\s+rp|\s+\d|\s+buat|\s+untuk|$)',
      caseSensitive: false,
    );
    final debtMatch = debtRegex.firstMatch(cleanSegment);
    if (debtMatch != null) {
      final contact = _cleanContactName(debtMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'hutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'hutang', contact),
        date: date,
      );
    }

    // Kasus Hutang 2: Belum dibayar / bayar kepada/ke [nama] (misal: "Pembelian es kelapa sebesar 6.000 belum dibayar kepada Dani")
    final unpaidDebtRegex = RegExp(
      r'\b(?:belum\s+(?:di)?bayar(?:kan)?|nunggak|utang|ngutang)\s+(?:ke|kepada|sama)\s+([A-Za-z0-9_\s]+?)(?:\.|$|\s+sebesar|\s+sejumlah|\s+senilai|\s+sebanyak|\s+\d|\s+buat|\s+untuk)',
      caseSensitive: false,
    );
    final unpaidDebtMatch = unpaidDebtRegex.firstMatch(cleanSegment);
    if (unpaidDebtMatch != null) {
      final contact = _cleanContactName(unpaidDebtMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'hutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'hutang', contact),
        date: date,
      );
    }

    // Kasus Piutang: meminjamkan ke [nama], pinjamkan ke [nama], kasih pinjam ke [nama], dipinjam oleh [nama]
    final loanRegex = RegExp(
      r'\b(?:meminjamkan\s+(?:uang\s+)?ke|pinjamkan\s+ke|kasih\s+pinjam\s+ke|pinjami|dipinjam\s+(?:oleh|sama))\s+([A-Za-z0-9_\s]+?)(?:\s+sebesar|\s+sejumlah|\s+senilai|\s+sebanyak|\s+sebesar\s+rp|\s+rp|\s+\d|\s+buat|\s+untuk|$)',
      caseSensitive: false,
    );
    final loanMatch = loanRegex.firstMatch(cleanSegment);
    if (loanMatch != null) {
      final contact = _cleanContactName(loanMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'piutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'piutang', contact),
        date: date,
      );
    }

    // Kasus Piutang alternatif: "[Nama] pinjam uang ke saya"
    final altLoanRegex = RegExp(
      r'\b([A-Za-z0-9_]+)\s+pinjam\s+(?:uang\s+)?(?:ke\s+saya|sama\s+saya)',
      caseSensitive: false,
    );
    final altLoanMatch = altLoanRegex.firstMatch(cleanSegment);
    if (altLoanMatch != null) {
      final contact = _cleanContactName(altLoanMatch.group(1));
      return VoiceIntentModel(
        feature: 'hutang_piutang',
        type: 'piutang',
        amount: amount,
        contactName: contact,
        note: _extractNote(cleanSegment, 'piutang', contact),
        date: date,
      );
    }

    // ── 2. Deteksi Penyesuaian Saldo (Ngepasin Saldo) ──────────────────────
    final adjustmentIntent = _detectBalanceAdjustment(cleanSegment, amount, date);
    if (adjustmentIntent != null) {
      return adjustmentIntent;
    }

    // ── 3. Deteksi Transfer Antar Dompet vs Pemasukan ──────────────────────
    final isIncome = _isIncomeIntent(lower);

    if (!isIncome) {
      // Pola 1: [transfer/pindah/kirim] [uang/saldo/dana] [dari] [From] ke [To]
      // Contoh: "Transfer uang dari Jago ke BNI sebesar Rp226.000", "Pindah dana dari BCA ke Gopay", "Tf uang Jago ke BNI"
      final transferFromToRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?(?:dari\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 2: [transfer/pindah/kirim] [uang/saldo/dana] ke [To] [dari/pakai/via] [From]
      // Contoh: "Transfer uang ke BNI dari Jago", "Transfer ke BNI pakai BCA 50rb"
      final transferToFromRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:dari|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 3: [top up/isi saldo] [To] [dari/pakai/via] [From]
      // Contoh: "Top up Dana dari Jago", "Topup gopay 50rb pakai BCA", "Isi saldo ShopeePay via Mandiri"
      final topupFromRegex = RegExp(
        r'\b(?:top\s*up|topup|isi\s+saldo)\s+(?:ke\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)(?:\s+(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*))?\s*(?:dari|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 4: [top up/isi saldo] [To] (tanpa asal)
      // Contoh: "Top up Gopay 50rb", "Isi saldo ShopeePay 100k"
      final topupToOnlyRegex = RegExp(
        r'\b(?:top\s*up|topup|isi\s+saldo)\s+(?:ke\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      // Pola 5: [transfer/pindah/kirim] [uang/saldo/dana] ke [To] (tanpa asal)
      // Contoh: "Transfer uang ke BNI sebesar 200rb", "Pindah saldo ke BCA"
      final transferToOnlyRegex = RegExp(
        r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf)\s+(?:uang\s+|saldo\s+|dana\s+)?(?:sebesar\s+[\d.,\s\w]+|\d+[\d.,\w]*\s+)?ke\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)',
        caseSensitive: false,
      );

      final matchFromTo = transferFromToRegex.firstMatch(cleanSegment);
      final matchToFrom = transferToFromRegex.firstMatch(cleanSegment);
      final matchTopupFrom = topupFromRegex.firstMatch(cleanSegment);
      final matchTopupToOnly = topupToOnlyRegex.firstMatch(cleanSegment);
      final matchTransferToOnly = transferToOnlyRegex.firstMatch(cleanSegment);

      final isTransferPhrase = RegExp(
        r'\b(?:transfer\s+uang|pindah\s+uang|pindah\s+saldo|transfer\s+saldo|kirim\s+uang|kirim\s+saldo|tf\s+uang|top\s*up|isi\s+saldo)\b',
        caseSensitive: false,
      ).hasMatch(cleanSegment);

      if (matchFromTo != null || matchToFrom != null || matchTopupFrom != null || matchTopupToOnly != null || matchTransferToOnly != null || isTransferPhrase) {
        String? fromW;
        String? toW;

        if (matchFromTo != null) {
          fromW = _cleanWalletCandidate(matchFromTo.group(1));
          toW = _cleanWalletCandidate(matchFromTo.group(2));
        } else if (matchToFrom != null) {
          toW = _cleanWalletCandidate(matchToFrom.group(1));
          fromW = _cleanWalletCandidate(matchToFrom.group(2));
        } else if (matchTopupFrom != null) {
          toW = _cleanWalletCandidate(matchTopupFrom.group(1));
          fromW = _cleanWalletCandidate(matchTopupFrom.group(2));
        } else if (matchTopupToOnly != null) {
          toW = _cleanWalletCandidate(matchTopupToOnly.group(1));
        } else if (matchTransferToOnly != null) {
          toW = _cleanWalletCandidate(matchTransferToOnly.group(1));
        }

        // Jika fromW belum terdeteksi dari pola khusus, cari dari klausa preposisi "dari [wallet]" atau wallet umum
        fromW ??= _extractSourceWalletForTransfer(cleanSegment, excludedWallet: toW);

        final normFrom = fromW != null ? _normalizeWalletName(fromW) : null;
        final normTo = toW != null ? _normalizeWalletName(toW) : null;

        return VoiceIntentModel(
          feature: 'transfer',
          amount: amount,
          fromWallet: normFrom,
          toWallet: normTo,
          note: _extractNote(cleanSegment, 'transfer', null, normFrom, normTo),
          date: date,
        );
      }
    }

    // ── 3. Deteksi Pemasukan (Income) ─────────────────────────────────────────
    if (isIncome) {
      final category = _detectCategory(lower, isIncome: true);
      final wallet = _extractWallet(cleanSegment);
      return VoiceIntentModel(
        feature: 'transaksi',
        type: 'income',
        amount: amount,
        category: category,
        wallet: wallet,
        note: _extractNote(cleanSegment, 'income', null, wallet),
        date: date,
      );
    }

    // ── 4. Default: Pengeluaran (Expense) ────────────────────────────────────
    final category = _detectCategory(lower, isIncome: false);
    final wallet = _extractWallet(cleanSegment);
    return VoiceIntentModel(
      feature: 'transaksi',
      type: 'expense',
      amount: amount,
      category: category,
      wallet: wallet,
      note: _extractNote(cleanSegment, 'expense', null, wallet),
      date: date,
    );
  }

  /// Deteksi Intent Penyesuaian Saldo / Ngepasin Saldo
  VoiceIntentModel? _detectBalanceAdjustment(String cleanSegment, double? amount, DateTime? date) {
    if (amount == null) return null;
    final lower = cleanSegment.toLowerCase();

    // 1. Cek apakah ada indikasi kata kunci adjustment
    final hasAdjustmentKeyword = RegExp(
      r'\b(?:ngepasin|pasin|paskan|sesuaikan|koreksi|seharusnya|harusnya|mestinya|aslinya|riilnya|saldo\s+riil|saldo\s+fisik|saldo\s+nyata|saldo\s+sebenarnya|saldo\s+asli)\b',
      caseSensitive: false,
    ).hasMatch(lower);

    // Pola kalimat locative: "di [wallet] (uangnya|duitnya|saldonya|dana)? (sekarang|saat ini|tinggal|ada|aslinya|riilnya) [nominal]"
    final isLocativeBalancePhrase = RegExp(
      r'\bdi\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:uangnya|duitnya|saldonya|dana)?\s*(?:sekarang|saat\s+ini|tinggal|ada|aslinya|riilnya|seharusnya|harusnya|mestinya)\b',
      caseSensitive: false,
    ).hasMatch(lower);

    // Pola kalimat kepemilikan saldo: "(uang|duit|saldo|dana) di [wallet] (sekarang|saat ini|tinggal|ada|aslinya|riilnya|seharusnya|harusnya|mestinya)"
    final isWalletBalancePhrase = RegExp(
      r'\b(?:uang|duit|saldo|dana)\s+(?:di\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:sekarang|saat\s+ini|tinggal|ada|aslinya|riilnya|seharusnya|harusnya|mestinya|jadi|ke|menjadi)\b',
      caseSensitive: false,
    ).hasMatch(lower);

    // Pola kalimat saldo wallet: "saldo [wallet] (seharusnya|harusnya|mestinya|aslinya|riilnya|jadi|ke|menjadi|ada|sekarang|tinggal)"
    final isSaldoWalletPhrase = RegExp(
      r'\bsaldo\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:seharusnya|harusnya|mestinya|aslinya|riilnya|fisik|nyata|sebenarnya|jadi|ke|menjadi|ada|sekarang|tinggal)\b',
      caseSensitive: false,
    ).hasMatch(lower);

    // Pola kalimat reverse: "[wallet] seharusnya/harusnya/mestinya [nominal]" atau "[wallet] saldonya sekarang/tinggal [nominal]"
    final isWalletShouldBePhrase = RegExp(
      r'\b(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:seharusnya|harusnya|mestinya|saldonya\s+sekarang|saldonya\s+tinggal|saldonya\s+aslinya)\b',
      caseSensitive: false,
    ).hasMatch(lower);

    if (!hasAdjustmentKeyword && !isLocativeBalancePhrase && !isWalletBalancePhrase && !isSaldoWalletPhrase && !isWalletShouldBePhrase) {
      return null;
    }

    // Ekstrak wallet
    String? wallet;

    // 1. Cek dari "di [wallet]"
    final locMatch = RegExp(
      r'\bdi\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\b',
      caseSensitive: false,
    ).firstMatch(lower);
    if (locMatch != null) {
      final cand = _cleanWalletCandidate(locMatch.group(1));
      if (_isKnownOrValidWallet(cand)) {
        wallet = cand;
      }
    }

    // 2. Cek dari "saldo [wallet]" atau "saldo riil/fisik/nyata [wallet]"
    if (wallet == null) {
      final saldoMatch = RegExp(
        r'\bsaldo\s+(?:riil\s+|fisik\s+|nyata\s+|asli\s+|sebenarnya\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\b',
        caseSensitive: false,
      ).firstMatch(lower);
      if (saldoMatch != null) {
        final cand = _cleanWalletCandidate(saldoMatch.group(1));
        if (_isKnownOrValidWallet(cand)) {
          wallet = cand;
        }
      }
    }

    // 3. Cek dari "[wallet] seharusnya / harusnya / mestinya / aslinya"
    if (wallet == null) {
      final shouldMatch = RegExp(
        r'\b(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\s+(?:seharusnya|harusnya|mestinya|aslinya|saldonya)\b',
        caseSensitive: false,
      ).firstMatch(lower);
      if (shouldMatch != null) {
        final cand = _cleanWalletCandidate(shouldMatch.group(1));
        if (_isKnownOrValidWallet(cand)) {
          wallet = cand;
        }
      }
    }

    // 4. Cek dari aksi: "ngepasin / pasin / sesuaikan [wallet]"
    if (wallet == null) {
      final actionMatch = RegExp(
        r'\b(?:ngepasin|pasin|paskan|sesuaikan|koreksi|atur|set|update)\s+(?:saldo\s+)?(?:riil\s+|fisik\s+|nyata\s+|asli\s+)?(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?([A-Za-z0-9_]+)\b',
        caseSensitive: false,
      ).firstMatch(lower);
      if (actionMatch != null) {
        final cand = _cleanWalletCandidate(actionMatch.group(1));
        if (_isKnownOrValidWallet(cand)) {
          wallet = cand;
        }
      }
    }

    // Fallback general wallet extraction
    wallet ??= _extractWallet(cleanSegment);

    final normWallet = wallet != null ? _normalizeWalletName(wallet) : null;
    final note = _extractAdjustmentNote(cleanSegment, normWallet);

    return VoiceIntentModel(
      feature: 'penyesuaian_saldo',
      type: 'adjustment',
      amount: amount,
      wallet: normWallet,
      note: note,
      date: date,
    );
  }

  /// Cek apakah kandidat kata adalah nama wallet yang valid / dikenal
  bool _isKnownOrValidWallet(String? candidate) {
    if (candidate == null || candidate.trim().isEmpty) return false;
    final lower = candidate.trim().toLowerCase();
    const stopWords = [
      'uang', 'uangnya', 'duit', 'duitnya', 'saldo', 'saldonya', 'dana', 'dananya',
      'riil', 'riilnya', 'fisik', 'fisiknya', 'nyata', 'nyatanya', 'asli', 'aslinya', 'sebenarnya',
      'seharusnya', 'harusnya', 'mestinya', 'sekarang', 'tinggal',
      'ada', 'jadi', 'ke', 'menjadi', 'sebesar', 'senilai', 'sejumlah', 'ini', 'itu',
    ];
    if (stopWords.contains(lower)) return false;
    return true;
  }

  /// Membersihkan catatan khusus intent penyesuaian saldo
  String _extractAdjustmentNote(String segment, String? wallet) {
    var note = segment.trim();

    // 1. Buang hashtag
    note = note.replaceAll(RegExp(r'#\s*[\w\s&-]+', caseSensitive: false), ' ').trim();

    // 2. Buang tag kategori Mind Space umum
    note = note.replaceAll(RegExp(r'\b(?:Shopping|Daily Life|Food & Drink|Finance|Personal|Work|Life|Remarks)\b', caseSensitive: false), ' ').trim();

    // 3. Buang klausa nominal
    note = note.replaceAll(RegExp(r'\s*(?:sebesar|sejumlah|senilai|seharga|nominal|total|harga)?\s*(?:Rp\.?\s*)?\d[\d.,]*\s*(?:juta|jt|million|ribu|rb|k)?', caseSensitive: false), ' ').trim();

    // 4. Buang kata kunci adjustment & kata sambung
    note = note.replaceAll(
      RegExp(
        r'\b(?:ngepasin|pasin|paskan|sesuaikan|koreksi|seharusnya|harusnya|mestinya|aslinya|riilnya|fisik|nyata|sebenarnya|saldo\s+riil|saldo\s+fisik|saldo\s+nyata|saldo\s+sebenarnya|saldo\s+asli|saldo|uangnya|duitnya|saldonya|uang|duit|dana|sekarang|saat\s+ini|tinggal|ada|jadi|ke|menjadi|di|pada|rekening|bank|dompet|akun|kartu)\b',
        caseSensitive: false,
      ),
      ' ',
    ).trim();

    if (wallet != null && wallet.isNotEmpty) {
      note = note.replaceAll(RegExp('\\b${RegExp.escape(wallet)}\\b', caseSensitive: false), ' ').trim();
    }

    note = _cleanDatePhrases(note);
    note = note.replaceAll(RegExp(r'\s+'), ' ').trim();

    if (note.isEmpty || note.length <= 2) {
      return 'Penyesuaian saldo ${wallet ?? 'Dompet'}'.trim();
    }

    return note[0].toUpperCase() + note.substring(1);
  }

  /// Ekstraksi nilai nominal double dari kalimat
  double? _extractAmount(String text) {
    // 1. Kasus dengan satuan juta: "1.5 jt", "2 juta", "1,5juta"
    final jtMatch = RegExp(r'(\d+(?:[.,]\d+)?)\s*(?:juta|jt|million)\b', caseSensitive: false).firstMatch(text);
    if (jtMatch != null) {
      final numStr = jtMatch.group(1)!.replaceAll(',', '.');
      final val = double.tryParse(numStr);
      if (val != null) return val * 1000000;
    }

    // 2. Kasus dengan satuan ribu: "25rb", "25 ribu", "50k", "10.5 rb"
    final rbMatch = RegExp(r'(\d+(?:[.,]\d+)?)\s*(?:ribu|rb|k)\b', caseSensitive: false).firstMatch(text);
    if (rbMatch != null) {
      final numStr = rbMatch.group(1)!.replaceAll(',', '.');
      final val = double.tryParse(numStr);
      if (val != null) return val * 1000;
    }

    // 3. Format ribuan bertitik: "Rp25.000", "25.000", "1.500.000"
    final thousandMatch = RegExp(r'(?:Rp\.?\s*)?(\d{1,3}(?:\.\d{3})+(?:,\d+)?)', caseSensitive: false).firstMatch(text);
    if (thousandMatch != null) {
      final cleanNum = thousandMatch.group(1)!.replaceAll('.', '').replaceAll(',', '.');
      final val = double.tryParse(cleanNum);
      if (val != null) return val;
    }

    // 4. Format angka polos: "Rp 25000", "sebesar 50000"
    final plainMatch = RegExp(r'(?:Rp\.?\s*|sebesar\s+|seharga\s+|sejumlah\s+)(\d+)\b', caseSensitive: false).firstMatch(text);
    if (plainMatch != null) {
      return double.tryParse(plainMatch.group(1)!);
    }

    // 5. Fallback angka apa saja di atas 100
    final anyNumMatch = RegExp(r'\b(\d{4,})\b').firstMatch(text);
    if (anyNumMatch != null) {
      return double.tryParse(anyNumMatch.group(1)!);
    }

    return null;
  }

  /// Cek apakah kalimat mengindikasikan pemasukan
  bool _isIncomeIntent(String text) {
    const incomeKeywords = [
      'gaji',
      'salary',
      'upah',
      'honor',
      'penghasilan',
      'pendapatan',
      'pemasukan',
      'income',
      'terima uang',
      'dapat uang',
      'dapat transfer',
      'ditransfer',
      'dikirimkan uang',
      'dikirim uang',
      'dikirimi uang',
      'dapat kiriman',
      'terima transfer',
      'bonus',
      'thr',
      'cashback',
      'komisi',
      'freelance',
      'proyek',
      'hasil jualan',
      'jual',
      'jualan',
      'laba',
      'profit',
      'omset',
      'omzet',
      'dividen',
      'hadiah',
      'gift',
      'angpao',
    ];
    for (final kw in incomeKeywords) {
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return true;
      }
    }
    return false;
  }

  /// Deteksi kategori otomatis dari kata kunci
  String? _detectCategory(String text, {required bool isIncome}) {
    if (isIncome) {
      if (text.contains('jual') || text.contains('jualan') || text.contains('dagang') || text.contains('bisnis') || text.contains('omset') || text.contains('omzet') || text.contains('freelance') || text.contains('komisi') || text.contains('proyek')) {
        return 'Penjualan';
      }
      if (text.contains('dividen') || text.contains('investasi') || text.contains('saham') || text.contains('crypto') || text.contains('reksadana') || text.contains('bunga')) {
        return 'Investasi';
      }
      if (text.contains('bonus') || text.contains('thr') || text.contains('hadiah') || text.contains('gift') || text.contains('angpao') || text.contains('reward') || text.contains('cashback')) {
        return 'Bonus';
      }
      if (text.contains('gaji') || text.contains('salary') || text.contains('upah') || text.contains('honor') || text.contains('penghasilan') || text.contains('pendapatan')) {
        return 'Gaji';
      }
      if (text.contains('kirim') || text.contains('transfer') || text.contains('dikirimi')) {
        return 'Hadiah';
      }
      return 'Lainnya';
    }

    // Expense Categories
    const categoryMap = <String, List<String>>{
      'Makanan & Minuman': [
        'makan',
        'minum',
        'sarapan',
        'siang',
        'malam',
        'jus',
        'alpukat',
        'avocado',
        'juice',
        'smoothie',
        'kopi',
        'coffee',
        'teh',
        'es teh',
        'esteh',
        'boba',
        'susu',
        'milk',
        'yogurt',
        'air mineral',
        'aqua',
        'nasipadang',
        'nasi padang',
        'nasi',
        'nasgor',
        'padang',
        'mi ayam',
        'mie ayam',
        'miayam',
        'mieayam',
        'mie',
        'bakso',
        'ayam',
        'bebek',
        'ikan',
        'seafood',
        'kafe',
        'cafe',
        'resto',
        'restoran',
        'jajan',
        'snack',
        'cemilan',
        'burger',
        'pizza',
        'gorengan',
        'martabak',
        'sate',
        'soto',
        'pecel',
        'geprek',
        'seblak',
        'batagor',
        'siomay',
        'cilok',
        'cireng',
        'roti',
        'toast',
        'donat',
        'kue',
        'es krim',
        'ice cream',
        'gelato',
        'dimsum',
        'ramen',
        'sushi',
        'pasta',
        'steak',
        'warteg',
        'gofood',
        'grabfood',
        'shopeefood',
        'buah',
        'sayur',
      ],
      'Transportasi': [
        'bensin',
        'pertalite',
        'pertamax',
        'solar',
        'bbm',
        'parkir',
        'tol',
        'gojek',
        'grab',
        'ojol',
        'maxim',
        'indrive',
        'angkot',
        'busway',
        'transjakarta',
        'kereta',
        'krl',
        'mrt',
        'lrt',
        'tiket',
        'tambal ban',
        'cuci motor',
        'cuci mobil',
        'service',
        'servis',
        'oli',
      ],
      'Belanja': [
        'belanja',
        'shopping',
        'baju',
        'kaos',
        'celana',
        'sepatu',
        'tas',
        'supermarket',
        'minimarket',
        'indomaret',
        'alfamart',
        'alfamidi',
        'shopee',
        'tokopedia',
        'lazada',
        'tiktok shop',
        'skincare',
        'sabun',
        'shampoo',
        'odol',
        'deterjen',
        'mall',
      ],
      'Tagihan & Utilitas': [
        'listrik',
        'token',
        'pln',
        'air',
        'pdam',
        'wifi',
        'indihome',
        'biznet',
        'first media',
        'pulsa',
        'paket data',
        'kuota',
        'bpjs',
        'pajak',
        'asuransi',
        'tagihan',
        'iuran',
        'sewa',
        'kost',
        'kos',
        'kontrakan',
      ],
      'Hiburan': [
        'bioskop',
        'cinema',
        'xxi',
        'cgv',
        'nonton',
        'film',
        'game',
        'topup game',
        'steam',
        'playstation',
        'spotify',
        'netflix',
        'youtube',
        'disney',
        'liburan',
        'staycation',
        'hotel',
        'wisata',
        'karaoke',
      ],
      'Kesehatan': [
        'obat',
        'dokter',
        'rumah sakit',
        'rs',
        'apotek',
        'vitamin',
        'klinik',
        'periksa',
        'terapi',
        'rapid',
        'masker',
      ],
      'Pendidikan': [
        'buku',
        'kursus',
        'course',
        'sekolah',
        'kuliah',
        'spp',
        'les',
        'ujian',
        'seminar',
        'workshop',
        'alat tulis',
      ],
    };

    for (final entry in categoryMap.entries) {
      for (final kw in entry.value) {
        if (RegExp('\\b${RegExp.escape(kw)}\\b', caseSensitive: false).hasMatch(text) ||
            (kw.length >= 4 && text.contains(kw.toLowerCase()))) {
          return entry.key;
        }
      }
    }

    return 'Lainnya';
  }

  /// Membersihkan nama kontak dari kata sambung
  String _cleanContactName(String? raw) {
    if (raw == null) return '';
    var name = raw.trim();
    // Buang preposisi di ujung
    name = name.replaceAll(RegExp(r'\s+(?:sebesar|sejumlah|senilai|sebanyak|rp|\d+).*$', caseSensitive: false), '');
    // Buang tanda baca di akhir
    name = name.replaceAll(RegExp(r'[.,;:!?]+$'), '');
    return name.trim();
  }

  /// Membersihkan kandidat nama wallet dari kata-kata umum
  String? _cleanWalletCandidate(String? raw) {
    if (raw == null) return null;
    final name = raw.replaceAll(RegExp(r'^(?:rekening|bank|dompet|akun|kartu)\s+', caseSensitive: false), '').trim();
    final lower = name.toLowerCase();
    const nonWalletWords = [
      'uang',
      'saldo',
      'sebesar',
      'sejumlah',
      'senilai',
      'rp',
      'ke',
      'dari',
      'saya',
      'kamu',
      'dia',
      'pindah',
      'transfer',
    ];
    if (nonWalletWords.contains(lower) || RegExp(r'^\d').hasMatch(lower)) {
      return null;
    }
    return name;
  }

  /// Ekstraksi wallet asal jika kalimat transfer tidak memiliki pola regex langsung
  String? _extractSourceWalletForTransfer(String text, {String? excludedWallet}) {
    // 1. Coba cari preposisi "dari [wallet]" atau "pakai [wallet]"
    final prepRegex = RegExp(
      r'\b(?:dari|pakai|pake|via|lewat|menggunakan|melalui)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?([A-Za-z0-9_]+)\b',
      caseSensitive: false,
    );
    final match = prepRegex.firstMatch(text);
    if (match != null) {
      final candidate = _cleanWalletCandidate(match.group(1));
      if (candidate != null && (excludedWallet == null || candidate.toLowerCase() != excludedWallet.toLowerCase())) {
        return candidate;
      }
    }

    // 2. Cek keyword wallet populer jika tidak sama dengan destination wallet
    const knownWallets = [
      'jago',
      'bca',
      'bri',
      'bni',
      'mandiri',
      'cimb',
      'permata',
      'seabank',
      'blu',
      'jenius',
      'bsi',
      'gopay',
      'gojek',
      'ovo',
      'dana',
      'shopeepay',
      'spay',
      'linkaja',
      'cash',
      'tunai',
      'dompet',
    ];
    for (final kw in knownWallets) {
      if (excludedWallet != null && kw.toLowerCase() == excludedWallet.toLowerCase()) {
        continue;
      }
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return kw;
      }
    }

    return null;
  }

  /// Ekstraksi nama rekening / wallet dari preposisi atau nama bank/e-wallet populer
  String? _extractWallet(String text) {
    // 1. Pola preposisi eksplisit: "dengan jago", "pakai bca", "pake gopay", "via ovo", "lewat dana", "dari dompet", "menggunakan spay", "pake rekening bni", "dilakukan menggunakan bni"
    final prepRegex = RegExp(
      r'\b(?:dilakukan\s+)?(?:dengan|pakai|pake|via|lewat|menggunakan|by|melalui|dari)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?([A-Za-z0-9_]+(?:\s+[A-Za-z0-9_]+)?)\b',
      caseSensitive: false,
    );

    final match = prepRegex.firstMatch(text);
    if (match != null) {
      final candidate = match.group(1)!.trim();
      final lower = candidate.toLowerCase();
      const nonWalletWords = [
        'cepat',
        'mudah',
        'senang',
        'teman',
        'keluarga',
        'kawan',
        'uang',
        'rupiah',
        'sebesar',
        'sejumlah',
        'harga',
        'kemarin',
        'tadi',
        'malam',
        'siang',
        'pagi',
        'sore',
      ];
      if (!nonWalletWords.contains(lower) && !RegExp(r'^\d').hasMatch(lower)) {
        return _normalizeWalletName(candidate);
      }
    }

    // 2. Pola nama e-wallet / bank populer langsung jika ada di teks
    const knownWallets = [
      'jago',
      'bca',
      'bri',
      'bni',
      'mandiri',
      'cimb',
      'permata',
      'seabank',
      'blu',
      'jenius',
      'bsi',
      'gopay',
      'gojek',
      'ovo',
      'dana',
      'shopeepay',
      'spay',
      'linkaja',
      'cash',
      'tunai',
      'dompet',
    ];
    for (final kw in knownWallets) {
      if (RegExp('\\b$kw\\b', caseSensitive: false).hasMatch(text)) {
        return _normalizeWalletName(kw);
      }
    }

    return null;
  }

  /// Normalisasi nama wallet agar rapi dan kapitalisasi tepat
  String _normalizeWalletName(String raw) {
    var clean = raw.trim();
    final lower = clean.toLowerCase();
    if (lower == 'dompet utama' || lower == 'dompet' || lower == 'cash' || lower == 'tunai' || lower == 'utama') {
      return 'Dompet Utama';
    }
    clean = clean.replaceAll(RegExp(r'^(?:rekening|bank|dompet|akun|kartu)\s+', caseSensitive: false), '').trim();
    final cleanLower = clean.toLowerCase();
    switch (cleanLower) {
      case 'jago':
      case 'bank jago':
        return 'Jago';
      case 'bca':
      case 'bank bca':
        return 'BCA';
      case 'bri':
      case 'bank bri':
        return 'BRI';
      case 'bni':
      case 'bank bni':
        return 'BNI';
      case 'mandiri':
      case 'bank mandiri':
        return 'Mandiri';
      case 'seabank':
      case 'sea bank':
        return 'SeaBank';
      case 'blu':
      case 'blu bca':
        return 'blu';
      case 'jenius':
      case 'bank btpn':
        return 'Jenius';
      case 'bsi':
      case 'bank bsi':
        return 'BSI';
      case 'cimb':
      case 'cimb niaga':
        return 'CIMB Niaga';
      case 'permata':
      case 'bank permata':
        return 'Permata';
      case 'gopay':
      case 'go-pay':
      case 'gojek':
        return 'Gojek';
      case 'ovo':
        return 'OVO';
      case 'dana':
        return 'Dana';
      case 'shopeepay':
      case 'shopee pay':
      case 'spay':
        return 'ShopeePay';
      case 'linkaja':
      case 'link aja':
        return 'LinkAja';
      case 'cash':
      case 'tunai':
      case 'dompet':
      case 'dompet utama':
      case 'utama':
        return 'Dompet Utama';
      default:
        return clean.split(' ').map((w) => w.isNotEmpty ? w[0].toUpperCase() + w.substring(1) : '').join(' ');
    }
  }

  /// Membersihkan teks kalimat menjadi catatan (note) yang ringkas (mis: "Batagor", "Ayam", "Es kelapa")
  String _extractNote(String segment, String intentType, String? contact, [String? wallet, String? toWallet]) {
    var note = segment.trim();

    // 1. Buang semua format hashtag atau tag metadata (misal: # Shopping, #Daily Life, dsb.)
    note = note.replaceAll(RegExp(r'#\s*[\w\s&-]+', caseSensitive: false), ' ').trim();

    // 2. Buang tag kategori Mind Space umum yang sering tertinggal di ujung / tengah
    note = note.replaceAll(RegExp(r'\b(?:Shopping|Daily Life|Food & Drink|Finance|Personal|Work|Life|Remarks)\b', caseSensitive: false), ' ').trim();

    // 3. Buang klausa nominal di mana pun berada (misal: "sebesar Rp25.000", "Rp 25.000", "25rb", "50k", dsb.)
    note = note.replaceAll(RegExp(r'\s*(?:sebesar|sejumlah|senilai|seharga|nominal|total|harga)?\s*(?:Rp\.?\s*)?\d[\d.,]*\s*(?:juta|jt|million|ribu|rb|k)?', caseSensitive: false), ' ').trim();

    // 4. Khusus transfer: bersihkan kata kerja transfer dan entitas wallet
    if (intentType == 'transfer') {
      note = note.replaceAll(RegExp(r'\b(?:transfer|pindah(?:kan)?|kirim(?:kan)?|tf|top\s*up|topup|isi\s+saldo)\s+(?:uang|saldo|dana)?', caseSensitive: false), ' ').trim();
      note = note.replaceAll(RegExp(r'\b(?:dari|ke|pakai|pake|via|lewat|menggunakan)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+)?[A-Za-z0-9_]+', caseSensitive: false), ' ').trim();
      if (toWallet != null && toWallet.isNotEmpty) {
        note = note.replaceAll(RegExp('\\b${RegExp.escape(toWallet)}\\b', caseSensitive: false), ' ').trim();
      }
    }

    // 5. Khusus hutang / piutang: bersihkan klausa "belum dibayar kepada [nama]", "ngutang ke [nama]", "pinjam dari [nama]", dsb.
    if (intentType == 'hutang' || intentType == 'piutang') {
      note = note.replaceAll(RegExp(r'\b(?:belum\s+(?:di)?bayar(?:kan)?|nunggak|utang|ngutang|pinjam|meminjamkan|pinjamkan|kasih\s+pinjam)\s+(?:ke|kepada|sama|dari|oleh)?(?:\s+[A-Za-z0-9_]+)?', caseSensitive: false), ' ').trim();
      if (contact != null && contact.isNotEmpty) {
        note = note.replaceAll(RegExp('\\b${RegExp.escape(contact)}\\b', caseSensitive: false), ' ').trim();
      }
    }

    // 6. Buang klausa metode pembayaran / wallet (misal: "dilakukan menggunakan BNI", "dengan jago", "pakai bca", "via gopay", "pake dana", "menggunakan BNI")
    note = note.replaceAll(RegExp(r'\s*(?:dilakukan\s+)?(?:dengan|pakai|pake|via|lewat|menggunakan|by|melalui|dari)\s+(?:rekening\s+|bank\s+|dompet\s+|akun\s+|kartu\s+)?[A-Za-z0-9_]+(?:\s+[A-Za-z0-9_]+)?', caseSensitive: false), ' ').trim();

    // Buang kata "dilakukan" yang berdiri sendiri
    note = note.replaceAll(RegExp(r'\b(?:dilakukan)\b', caseSensitive: false), ' ').trim();

    if (wallet != null && wallet.isNotEmpty) {
      note = note.replaceAll(RegExp('\\b${RegExp.escape(wallet)}\\b', caseSensitive: false), ' ').trim();
    }

    // 7. Buang sisa-sisa pola titik nominal seperti ".000" atau ",00"
    note = note.replaceAll(RegExp(r'[.,]\d{2,3}\b'), ' ').trim();

    // 8. Buang keterangan waktu dan tanggal
    note = _cleanDatePhrases(note);

    // 9. Buang kata sambung & kata kerja aksi di awal kalimat berulang kali
    var prev = '';
    while (prev != note) {
      prev = note;
      note = note.replaceFirst(RegExp(r'^(?:dan|serta|lalu|kemudian|terus|setelah itu)\s+', caseSensitive: false), '').trim();
      note = note.replaceFirst(RegExp(r'^(?:dilakukan\s+pembelian|dilakukan\s+pembayaran|dilakukan\s+transaksi|dilakukan|pembelian|beli|membeli|bayar|membayar|pembayaran|isi|order|pesan|jajan|belanja|dapat|terima|kirim)\s+', caseSensitive: false), '').trim();
    }

    // 10. Bersihkan sisa tanda baca liar di tengah atau ujung (misal "jus alpukat . " -> "jus alpukat")
    note = note.replaceAll(RegExp(r'\s+[.,;:!?]+\s*'), ' ');
    note = note.replaceAll(RegExp(r'^[^\w]+|[^\w]+$'), ' ').trim();

    // 11. Kompres spasi ganda
    note = note.replaceAll(RegExp(r'\s+'), ' ');

    // 12. Capitalize huruf pertama & fallback cerdas
    if (note.isEmpty) {
      switch (intentType) {
        case 'hutang':
          return 'Hutang ke ${contact ?? 'seseorang'}';
        case 'piutang':
          return 'Piutang ke ${contact ?? 'seseorang'}';
        case 'transfer':
          if (toWallet != null && toWallet.isNotEmpty) {
            return 'Transfer ke $toWallet';
          }
          return 'Transfer dana';
        case 'income':
          return 'Pemasukan';
        default:
          return 'Pengeluaran';
      }
    }

    return note[0].toUpperCase() + note.substring(1);
  }

  /// Ekstraksi tanggal cerdas (natural language + format tanggal)
  DateTime? _extractDate(String text) {
    final lower = text.toLowerCase();
    final now = DateTime.now();

    // 1. Relatif: Kemarin lusa / 2 hari lalu
    if (RegExp(r'\b(?:kemarin\s+lusa|kemaren\s+lusa|2\s+hari\s+(?:yang\s+)?lalu|dua\s+hari\s+(?:yang\s+)?lalu)\b').hasMatch(lower)) {
      return now.subtract(const Duration(days: 2));
    }

    // 2. Relatif: Kemarin / Kemaren / Semalam / Yesterday
    if (RegExp(r'\b(?:kemarin|kemaren|semalam|yesterday)\b').hasMatch(lower)) {
      return now.subtract(const Duration(days: 1));
    }

    // 3. Relatif: Lusa / Besok lusa / 2 hari lagi
    if (RegExp(r'\b(?:besok\s+lusa|lusa|2\s+hari\s+lagi|dua\s+hari\s+lagi)\b').hasMatch(lower)) {
      return now.add(const Duration(days: 2));
    }

    // 4. Relatif: Besok / Esok / Tomorrow / 1 hari lagi
    if (RegExp(r'\b(?:besok|esok|tomorrow|1\s+hari\s+lagi|sehari\s+lagi)\b').hasMatch(lower)) {
      return now.add(const Duration(days: 1));
    }

    // 5. Relatif: N hari lalu
    final nHariLaluMatch = RegExp(r'\b(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh)\s+hari\s+(?:yang\s+)?lalu\b').firstMatch(lower);
    if (nHariLaluMatch != null) {
      final days = _parseIndoNumber(nHariLaluMatch.group(1)!);
      if (days != null) return now.subtract(Duration(days: days));
    }

    // 6. Relatif: N hari lagi / ke depan
    final nHariLagiMatch = RegExp(r'\b(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh)\s+hari\s+(?:lagi|ke\s+depan)\b').firstMatch(lower);
    if (nHariLagiMatch != null) {
      final days = _parseIndoNumber(nHariLagiMatch.group(1)!);
      if (days != null) return now.add(Duration(days: days));
    }

    // 7. Relatif: N minggu / pekan lalu
    final nMingguLaluMatch = RegExp(r'\b(?:(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|se)\s+)?(?:minggu|pekan)\s+(?:yang\s+)?lalu\b').firstMatch(lower);
    if (nMingguLaluMatch != null) {
      final weeks = _parseIndoNumber(nMingguLaluMatch.group(1) ?? '1') ?? 1;
      return now.subtract(Duration(days: weeks * 7));
    }

    // 8. Relatif: N minggu / pekan depan / lagi
    final nMingguDepanMatch = RegExp(r'\b(?:(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|se)\s+)?(?:minggu|pekan)\s+(?:depan|lagi|ke\s+depan)\b').firstMatch(lower);
    if (nMingguDepanMatch != null) {
      final weeks = _parseIndoNumber(nMingguDepanMatch.group(1) ?? '1') ?? 1;
      return now.add(Duration(days: weeks * 7));
    }

    // 9. Relatif: N bulan lalu (contoh: "3 bulan lalu", "sebulan lalu", "bulan lalu")
    final nBulanLaluMatch = RegExp(r'\b(?:(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|sebelas|dua\s+belas|duabelas|se)\s+)?bulan\s+(?:yang\s+)?lalu\b').firstMatch(lower);
    if (nBulanLaluMatch != null) {
      final months = _parseIndoNumber(nBulanLaluMatch.group(1) ?? '1') ?? 1;
      return _shiftMonths(now, -months);
    }

    // 10. Relatif: N bulan lagi / depan
    final nBulanDepanMatch = RegExp(r'\b(?:(\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|sebelas|dua\s+belas|duabelas|se)\s+)?bulan\s+(?:depan|lagi|ke\s+depan)\b').firstMatch(lower);
    if (nBulanDepanMatch != null) {
      final months = _parseIndoNumber(nBulanDepanMatch.group(1) ?? '1') ?? 1;
      return _shiftMonths(now, months);
    }

    // 11. Relatif: N tahun lalu
    final nTahunLaluMatch = RegExp(r'\b(?:(\d+|satu|dua|tiga|empat|lima|se)\s+)?tahun\s+(?:yang\s+)?lalu\b').firstMatch(lower);
    if (nTahunLaluMatch != null) {
      final years = _parseIndoNumber(nTahunLaluMatch.group(1) ?? '1') ?? 1;
      return _shiftYears(now, -years);
    }

    // 12. Hari dalam seminggu lalu: "senin lalu", "senin kemarin", "hari senin lalu"
    final dayOfWeekMatch = RegExp(r'\b(?:hari\s+)?(senin|selasa|rabu|kamis|jumat|jum' "'" r'?at|sabtu|minggu)\s+(?:lalu|kemarin)\b').firstMatch(lower);
    if (dayOfWeekMatch != null) {
      final targetWk = _parseDayOfWeek(dayOfWeekMatch.group(1)!);
      if (targetWk != null) {
        int diff = now.weekday - targetWk;
        if (diff <= 0) diff += 7;
        return now.subtract(Duration(days: diff));
      }
    }

    // 13. Format Tanggal ISO: YYYY-MM-DD (e.g. 2026-09-14)
    final isoMatch = RegExp(r'\b(\d{4})-(\d{1,2})-(\d{1,2})\b').firstMatch(lower);
    if (isoMatch != null) {
      final y = int.tryParse(isoMatch.group(1)!);
      final m = int.tryParse(isoMatch.group(2)!);
      final d = int.tryParse(isoMatch.group(3)!);
      if (y != null && m != null && d != null) {
        return DateTime(y, m, d, now.hour, now.minute, now.second);
      }
    }

    // 14. Format Tanggal Standard: DD/MM/YYYY atau DD-MM-YYYY
    final slashDateMatch = RegExp(r'\b(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})\b').firstMatch(lower);
    if (slashDateMatch != null) {
      final d = int.tryParse(slashDateMatch.group(1)!);
      final m = int.tryParse(slashDateMatch.group(2)!);
      var y = int.tryParse(slashDateMatch.group(3)!);
      if (y != null && y < 100) y += 2000;
      if (d != null && m != null && y != null) {
        return DateTime(y, m, d, now.hour, now.minute, now.second);
      }
    }

    // 15. Format Tanggal Teks: "14 September 2026", "tanggal 14 Sep", "14 September"
    final textDateMatch = RegExp(
      r'\b(?:tanggal|tgl)?\s*(\d{1,2})\s+(januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember|jan|feb|mar|apr|may|jun|jul|aug|agu|sep|okt|oct|nov|nop|dec|des)(?:\s+(\d{4}))?\b',
    ).firstMatch(lower);
    if (textDateMatch != null) {
      final d = int.tryParse(textDateMatch.group(1)!);
      final m = _parseMonthName(textDateMatch.group(2)!);
      final y = textDateMatch.group(3) != null ? int.tryParse(textDateMatch.group(3)!) : now.year;
      if (d != null && m != null && y != null) {
        return DateTime(y, m, d, now.hour, now.minute, now.second);
      }
    }

    // 16. Tanggal Hari Ini / Tadi
    if (RegExp(r'\b(?:hari\s+ini|today|tadi\s+pagi|tadi\s+siang|tadi\s+sore|tadi\s+malam|tadi)\b').hasMatch(lower)) {
      return now;
    }

    // 17. Tanggal saja tanpa bulan: "tanggal 14", "tgl 25"
    final onlyDateMatch = RegExp(r'\b(?:tanggal|tgl)\s+(\d{1,2})\b').firstMatch(lower);
    if (onlyDateMatch != null) {
      final d = int.tryParse(onlyDateMatch.group(1)!);
      if (d != null && d >= 1 && d <= 31) {
        final daysInMonth = DateTime(now.year, now.month + 1, 0).day;
        final validD = d > daysInMonth ? daysInMonth : d;
        return DateTime(now.year, now.month, validD, now.hour, now.minute, now.second);
      }
    }

    return null;
  }

  /// Membersihkan frasa penunjuk tanggal & waktu dari catatan transaksi
  String _cleanDatePhrases(String text) {
    var clean = text;

    // Bersihkan penanda tanggal eksplisit (e.g. "tanggal 14 September 2026", "14 September", "tgl 15")
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:tanggal|tgl)?\s*\d{1,2}\s+(?:januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember|jan|feb|mar|apr|may|jun|jul|aug|agu|sep|okt|oct|nov|nop|dec|des)(?:\s+\d{4})?\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan DD/MM/YYYY atau YYYY-MM-DD
    clean = clean.replaceAll(RegExp(r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b'), ' ');
    clean = clean.replaceAll(RegExp(r'\b\d{4}-\d{2}-\d{2}\b'), ' ');

    // Bersihkan "tanggal 14", "tgl 20"
    clean = clean.replaceAll(RegExp(r'\b(?:pada\s+)?(?:tanggal|tgl)\s+\d{1,2}\b', caseSensitive: false), ' ');

    // Bersihkan "kemarin lusa", "kemarin malam", "kemarin", "kemaren", "semalam", "hari ini", "besok lusa", "besok", "lusa"
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:kemarin\s+lusa|kemaren\s+lusa|besok\s+lusa|kemarin\s+malam|kemaren\s+malam|kemarin\s+pagi|kemaren\s+pagi|kemarin\s+siang|kemaren\s+siang|kemarin\s+sore|kemaren\s+sore|kemarin|kemaren|semalam|hari\s+ini|besok|esok|lusa|today|yesterday|tomorrow)\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan "N hari / minggu / bulan / tahun lalu"
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|sebelas|dua\s+belas|duabelas|se)?\s*(?:hari|minggu|pekan|bulan|tahun)\s+(?:yang\s+)?lalu\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan "N hari / minggu / bulan / tahun lagi / depan"
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:\d+|satu|dua|tiga|empat|lima|enam|tujuh|delapan|sembilan|sepuluh|sebelas|dua\s+belas|duabelas|se)?\s*(?:hari|minggu|pekan|bulan|tahun)\s+(?:lagi|depan|ke\s+depan)\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan hari dalam seminggu ("senin lalu", "hari senin", dst)
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:hari\s+)?(?:senin|selasa|rabu|kamis|jumat|jum' "'" r'?at|sabtu|minggu)\s*(?:lalu|kemarin|depan)?\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan waktu detail ("tadi pagi", "pagi tadi", "tadi malam", "tadi sore", "tadi siang", "tadi", "siang ini", "pagi ini", "malam ini", "kemarin malam", "kemarin pagi", dsb)
    clean = clean.replaceAll(
      RegExp(
        r'\b(?:pada\s+)?(?:tadi\s+pagi|pagi\s+tadi|tadi\s+siang|siang\s+tadi|tadi\s+sore|sore\s+tadi|tadi\s+malam|malam\s+tadi|tadi|pagi\s+ini|siang\s+ini|sore\s+ini|malam\s+ini|kemarin\s+malam|kemaren\s+malam|kemarin\s+pagi|kemaren\s+pagi|kemarin\s+siang|kemaren\s+siang|kemarin\s+sore|kemaren\s+sore)\b',
        caseSensitive: false,
      ),
      ' ',
    );

    // Bersihkan kata sambung waktu seperti "pada", "pas" yang berdiri sendiri
    clean = clean.replaceAll(RegExp(r'\b(?:pada|pas\s+waktu|pas)\b', caseSensitive: false), ' ');

    return clean;
  }

  /// Shift bulan dengan penyesuaian batas tanggal maksimum dalam bulan tujuan
  DateTime _shiftMonths(DateTime base, int deltaMonths) {
    int newYear = base.year;
    int newMonth = base.month + deltaMonths;
    while (newMonth <= 0) {
      newMonth += 12;
      newYear -= 1;
    }
    while (newMonth > 12) {
      newMonth -= 12;
      newYear += 1;
    }
    final daysInTargetMonth = DateTime(newYear, newMonth + 1, 0).day;
    final newDay = base.day > daysInTargetMonth ? daysInTargetMonth : base.day;
    return DateTime(newYear, newMonth, newDay, base.hour, base.minute, base.second);
  }

  /// Shift tahun dengan penyesuaian tahun kabisat (29 Feb)
  DateTime _shiftYears(DateTime base, int deltaYears) {
    final newYear = base.year + deltaYears;
    final daysInTargetMonth = DateTime(newYear, base.month + 1, 0).day;
    final newDay = base.day > daysInTargetMonth ? daysInTargetMonth : base.day;
    return DateTime(newYear, base.month, newDay, base.hour, base.minute, base.second);
  }

  /// Parser angka teks bahasa Indonesia ke int
  int? _parseIndoNumber(String text) {
    final clean = text.trim().toLowerCase();
    final directNum = int.tryParse(clean);
    if (directNum != null) return directNum;
    switch (clean) {
      case 'se':
      case 'satu':
      case 'one':
      case '1':
        return 1;
      case 'dua':
      case 'two':
      case '2':
        return 2;
      case 'tiga':
      case 'three':
      case '3':
        return 3;
      case 'empat':
      case 'four':
      case '4':
        return 4;
      case 'lima':
      case 'five':
      case '5':
        return 5;
      case 'enam':
      case 'six':
      case '6':
        return 6;
      case 'tujuh':
      case 'seven':
      case '7':
        return 7;
      case 'delapan':
      case 'eight':
      case '8':
        return 8;
      case 'sembilan':
      case 'nine':
      case '9':
        return 9;
      case 'sepuluh':
      case 'ten':
      case '10':
        return 10;
      case 'sebelas':
      case '11':
        return 11;
      case 'dua belas':
      case 'duabelas':
      case '12':
        return 12;
      default:
        return null;
    }
  }

  /// Konversi nama bulan ke nomor bulan 1-12
  int? _parseMonthName(String monthStr) {
    final lower = monthStr.toLowerCase();
    if (lower.startsWith('jan')) return 1;
    if (lower.startsWith('feb')) return 2;
    if (lower.startsWith('mar')) return 3;
    if (lower.startsWith('apr')) return 4;
    if (lower.startsWith('mei') || lower.startsWith('may')) return 5;
    if (lower.startsWith('jun')) return 6;
    if (lower.startsWith('jul')) return 7;
    if (lower.startsWith('agu') || lower.startsWith('aug') || lower.startsWith('agt')) return 8;
    if (lower.startsWith('sep')) return 9;
    if (lower.startsWith('okt') || lower.startsWith('oct')) return 10;
    if (lower.startsWith('nop') || lower.startsWith('nov')) return 11;
    if (lower.startsWith('des') || lower.startsWith('dec')) return 12;
    return null;
  }

  /// Konversi nama hari ke int weekday DateTime (1 = Senin, 7 = Minggu)
  int? _parseDayOfWeek(String dayStr) {
    final lower = dayStr.toLowerCase();
    if (lower.contains('senin') || lower.contains('monday')) return DateTime.monday;
    if (lower.contains('selasa') || lower.contains('tuesday')) return DateTime.tuesday;
    if (lower.contains('rabu') || lower.contains('wednesday')) return DateTime.wednesday;
    if (lower.contains('kamis') || lower.contains('thursday')) return DateTime.thursday;
    if (lower.contains('jumat') || lower.contains("jum'at") || lower.contains('friday')) return DateTime.friday;
    if (lower.contains('sabtu') || lower.contains('saturday')) return DateTime.saturday;
    if (lower.contains('minggu') || lower.contains('ahad') || lower.contains('sunday')) return DateTime.sunday;
    return null;
  }
}
